#!/usr/bin/env python3
"""
Translate rAthena quest NPC dialogue from English to Brazilian Portuguese.
Only translates text inside mes "..." and select("...") patterns.
Does NOT change: variable names, function calls, NPC names in brackets,
item names, map names, coordinates, script logic, comments.
Uses informal Brazilian Portuguese WITHOUT accented characters.
"""
import os
import re
import sys

BASE = "N:/Users/tinch/Documents/Projetos/ragnarok"

# Ordered list of (pattern, replacement) tuples for regex substitution
# Applied in order, so more specific patterns should come first
PHRASE_PATTERNS = [
    # === Full sentence patterns (most specific first) ===

    # Common quest completion/reward phrases
    (r"Come back when you've finished your task and I will give you a small reward\.", "Volte quando terminar sua tarefa e eu te darei uma pequena recompensa."),
    (r"If you change your mind, please come back\.", "Se mudar de ideia, por favor volte."),
    (r"Ok then, well come back here if you change your mind\.", "Tudo bem entao, volte aqui se mudar de ideia."),
    (r"Are you sure that you want to stop hunting\?", "Tem certeza que quer parar de cacar?"),
    (r"Any progress that you've made will be erased", "Todo o progresso que voce fez sera apagado"),
    (r"Amazing, you did that with speed\.", "Incrivel, voce fez isso rapidamente."),

    # Hunting quest patterns
    (r"Have you finished hunting the (\d+) (.+?)\?", r"Voce ja terminou de cacar os \1 \2?"),
    (r"Hmm, I don't think you've hunted (\d+) yet\.\.\.", r"Hmm, acho que voce ainda nao cacou \1 ainda..."),
    (r"Remember, I need help hunting (.+?) so go and hunt (\d+) of them\.", r"Lembre-se, preciso de ajuda cacando \1 entao va e cace \2 deles."),
    (r"Please kill (\d+) (.+?)\.", r"Por favor, mate \1 \2."),
    (r"How many would you like to hunt\?", "Quantos voce gostaria de cacar?"),
    (r"Ah, ok I think you can help me out by hunting some (.+?)\.", r"Ah, ok, acho que voce pode me ajudar cacando alguns \1."),

    # Greetings
    (r"^Good [Mm]orning!$", "Bom dia!"),
    (r"^Good [Mm]orning\.$", "Bom dia."),
    (r"^Good evening!$", "Boa noite!"),
    (r"^Good evening\.$", "Boa noite."),
    (r"^Good afternoon!$", "Boa tarde!"),
    (r"^Hello!$", "Ola!"),
    (r"^Hello\.$", "Ola."),
    (r"^Hello$", "Ola"),
    (r"^Hello,", "Ola,"),
    (r"^Hi!$", "Oi!"),
    (r"^Hi\.$", "Oi."),
    (r"^Hi there\.$", "Oi."),
    (r"^Hey!$", "Ei!"),
    (r"^Hey\.$", "Ei."),
    (r"^Hey,$", "Ei,"),
    (r"^Hey there\.$", "Ei, ola."),
    (r"^Welcome!$", "Bem-vindo!"),
    (r"^Goodbye!$", "Adeus!"),
    (r"^Farewell!$", "Adeus!"),
    (r"^Farewell\.$", "Adeus."),
    (r"^Thank you!$", "Obrigado!"),
    (r"^Thank you\.$", "Obrigado."),
    (r"^Thank you so much!$", "Muito obrigado!"),
    (r"^Thank you so much\.$", "Muito obrigado."),
    (r"^Thank you very much!$", "Muito obrigado!"),
    (r"^Thank you very much\.$", "Muito obrigado."),
    (r"^Thanks!$", "Obrigado!"),
    (r"^Thanks\.$", "Obrigado."),
    (r"^Take care!$", "Cuide-se!"),
    (r"^Take care\.$", "Cuide-se."),
    (r"^Good luck!$", "Boa sorte!"),
    (r"^Good luck\.$", "Boa sorte."),

    # Exclamations
    (r"^Really\?!$", "Serio?!"),
    (r"^Really\?$", "Serio?"),
    (r"^What\?!$", "O que?!"),
    (r"^What\?$", "O que?"),
    (r"^Impossible!$", "Impossivel!"),
    (r"^Excellent!$", "Excelente!"),
    (r"^Perfect!$", "Perfeito!"),
    (r"^Perfect\.$", "Perfeito."),
    (r"^Great!$", "Otimo!"),
    (r"^Wonderful!$", "Maravilhoso!"),
    (r"^Interesting\.\.\.$", "Interessante..."),
    (r"^Interesting\.$", "Interessante."),
    (r"^Of course!$", "Claro!"),
    (r"^Of course\.$", "Claro."),
    (r"^Of course,$", "Claro,"),
    (r"^I see\.$", "Entendo."),
    (r"^I see!$", "Entendo!"),
    (r"^I see,$", "Entendo,"),
    (r"^I understand\.$", "Entendo."),
    (r"^Absolutely!$", "Com certeza!"),
    (r"^Exactly!$", "Exatamente!"),
    (r"^Indeed\.$", "De fato."),
    (r"^Indeed!$", "De fato!"),

    # Common questions
    (r"Who are you\?", "Quem e voce?"),
    (r"What do you want\?", "O que voce quer?"),
    (r"What happened\?", "O que aconteceu?"),
    (r"What is it\?", "O que e?"),
    (r"What's wrong\?", "O que esta errado?"),
    (r"What are you doing here\?", "O que voce esta fazendo aqui?"),
    (r"How can I help you\?", "Como posso te ajudar?"),
    (r"Are you ready\?", "Voce esta pronto?"),
    (r"Are you sure\?", "Tem certeza?"),
    (r"Do you understand\?", "Voce entende?"),

    # Common dialogue phrases
    (r"Wait a moment\.", "Espere um momento."),
    (r"Wait a moment!", "Espere um momento!"),
    (r"Be careful!", "Tenha cuidado!"),
    (r"Be careful\.", "Tenha cuidado."),
    (r"Don't worry\.", "Nao se preocupe."),
    (r"Don't worry!", "Nao se preocupe!"),
    (r"Don't worry,", "Nao se preocupe,"),
    (r"Don't forget", "Nao esqueca"),
    (r"Good bye\.", "Adeus."),
    (r"See you later\.", "Ate mais tarde."),
    (r"See you later!", "Ate mais tarde!"),

    # Common sentence starters and structures
    (r"^You look like ", "Voce parece "),
    (r"^You are ", "Voce e "),
    (r"^You have ", "Voce tem "),
    (r"^You need ", "Voce precisa "),
    (r"^You must ", "Voce deve "),
    (r"^You should ", "Voce deveria "),
    (r"^You can ", "Voce pode "),
    (r"^You will ", "Voce vai "),
    (r"^You know ", "Voce sabe "),
    (r"^You seem ", "Voce parece "),
    (r"^You don't ", "Voce nao "),
    (r"^You may ", "Voce pode "),

    (r"^I am ", "Eu sou "),
    (r"^I'm ", "Eu sou "),
    (r"^I was ", "Eu estava "),
    (r"^I have ", "Eu tenho "),
    (r"^I've ", "Eu "),
    (r"^I need ", "Eu preciso "),
    (r"^I want ", "Eu quero "),
    (r"^I will ", "Eu vou "),
    (r"^I'll ", "Eu vou "),
    (r"^I can ", "Eu posso "),
    (r"^I can't ", "Eu nao posso "),
    (r"^I could ", "Eu poderia "),
    (r"^I couldn't ", "Eu nao poderia "),
    (r"^I don't ", "Eu nao "),
    (r"^I didn't ", "Eu nao "),
    (r"^I know ", "Eu sei "),
    (r"^I think ", "Eu acho "),
    (r"^I believe ", "Eu acredito "),
    (r"^I hope ", "Eu espero "),
    (r"^I wish ", "Eu desejo "),
    (r"^I remember ", "Eu me lembro "),
    (r"^I forgot ", "Eu esqueci "),
    (r"^I heard ", "Eu ouvi "),
    (r"^I see\b", "Eu vejo"),
    (r"^I would ", "Eu iria "),
    (r"^I must ", "Eu devo "),
    (r"^I shall ", "Eu devo "),
    (r"^I might ", "Eu poderia "),
    (r"^I should ", "Eu deveria "),
    (r"^I also ", "Eu tambem "),
    (r"^I just ", "Eu apenas "),
    (r"^I still ", "Eu ainda "),
    (r"^I never ", "Eu nunca "),
    (r"^I always ", "Eu sempre "),
    (r"^I only ", "Eu apenas "),
    (r"^I really ", "Eu realmente "),
    (r"^I finally ", "Eu finalmente "),
    (r"^I actually ", "Na verdade eu "),
    (r"^I already ", "Eu ja "),

    (r"^We are ", "Nos somos "),
    (r"^We have ", "Nos temos "),
    (r"^We need ", "Nos precisamos "),
    (r"^We must ", "Nos devemos "),
    (r"^We can ", "Nos podemos "),
    (r"^We will ", "Nos vamos "),
    (r"^We should ", "Nos deveriamos "),
    (r"^We don't ", "Nos nao "),

    (r"^He is ", "Ele e "),
    (r"^He was ", "Ele estava "),
    (r"^He has ", "Ele tem "),
    (r"^He will ", "Ele vai "),
    (r"^He can ", "Ele pode "),
    (r"^He doesn't ", "Ele nao "),
    (r"^He didn't ", "Ele nao "),

    (r"^She is ", "Ela e "),
    (r"^She was ", "Ela estava "),
    (r"^She has ", "Ela tem "),
    (r"^She will ", "Ela vai "),
    (r"^She can ", "Ela pode "),
    (r"^She doesn't ", "Ela nao "),

    (r"^They are ", "Eles sao "),
    (r"^They have ", "Eles tem "),
    (r"^They will ", "Eles vao "),
    (r"^They can ", "Eles podem "),
    (r"^They don't ", "Eles nao "),
    (r"^They were ", "Eles estavam "),

    (r"^It is ", "E "),
    (r"^It's ", "E "),
    (r"^It was ", "Era "),
    (r"^It will ", "Vai "),
    (r"^It can ", "Pode "),
    (r"^It has ", "Tem "),
    (r"^It seems ", "Parece "),

    (r"^There is ", "Ha "),
    (r"^There are ", "Ha "),
    (r"^There was ", "Havia "),
    (r"^There were ", "Havia "),
    (r"^There's ", "Ha "),

    (r"^This is ", "Isso e "),
    (r"^This was ", "Isso era "),
    (r"^That is ", "Isso e "),
    (r"^That's ", "Isso e "),
    (r"^That was ", "Isso era "),
    (r"^These are ", "Esses sao "),
    (r"^Those are ", "Aqueles sao "),

    (r"^Please ", "Por favor "),
    (r"^Let me ", "Deixe-me "),
    (r"^Let's ", "Vamos "),
    (r"^Come ", "Venha "),
    (r"^Go ", "Va "),
    (r"^Look ", "Olhe "),
    (r"^Listen ", "Escute "),
    (r"^Tell me ", "Me diga "),
    (r"^Give me ", "Me de "),
    (r"^Bring me ", "Traga para mim "),
    (r"^Show me ", "Me mostre "),
    (r"^Help me ", "Me ajude "),
    (r"^Follow me", "Siga-me"),
    (r"^Wait!", "Espere!"),
    (r"^Wait\.", "Espere."),
    (r"^Stop!", "Pare!"),

    (r"^Do you ", "Voce "),
    (r"^Did you ", "Voce "),
    (r"^Can you ", "Voce pode "),
    (r"^Could you ", "Voce poderia "),
    (r"^Would you ", "Voce "),
    (r"^Will you ", "Voce vai "),
    (r"^Have you ", "Voce "),
    (r"^Are you ", "Voce esta "),
    (r"^Were you ", "Voce estava "),

    (r"^However, ", "Porem, "),
    (r"^However ", "Porem "),
    (r"^But ", "Mas "),
    (r"^And ", "E "),
    (r"^So ", "Entao "),
    (r"^Then ", "Entao "),
    (r"^Also, ", "Alem disso, "),
    (r"^Also ", "Tambem "),
    (r"^Actually, ", "Na verdade, "),
    (r"^Actually ", "Na verdade "),
    (r"^Although ", "Embora "),
    (r"^Even ", "Mesmo "),
    (r"^Still, ", "Ainda assim, "),
    (r"^Still ", "Ainda "),
    (r"^Perhaps ", "Talvez "),
    (r"^Maybe ", "Talvez "),
    (r"^If ", "Se "),
    (r"^When ", "Quando "),
    (r"^While ", "Enquanto "),
    (r"^After ", "Depois "),
    (r"^Before ", "Antes "),
    (r"^During ", "Durante "),
    (r"^Since ", "Desde "),
    (r"^Because ", "Porque "),
    (r"^Until ", "Ate "),
    (r"^Unless ", "A menos que "),
    (r"^Once ", "Uma vez "),
    (r"^Suddenly,? ", "De repente, "),
    (r"^Unfortunately,? ", "Infelizmente, "),
    (r"^Fortunately,? ", "Felizmente, "),
    (r"^Apparently,? ", "Aparentemente, "),
    (r"^Obviously,? ", "Obviamente, "),
    (r"^Anyway,? ", "De qualquer forma, "),
    (r"^Alright,? ", "Tudo bem, "),
    (r"^Well,? ", "Bem, "),
    (r"^Now,? ", "Agora, "),
    (r"^Today ", "Hoje "),
    (r"^Tomorrow ", "Amanha "),
    (r"^Yesterday ", "Ontem "),

    # Common mid-sentence patterns (word-level, only applied to remaining English)
    (r"\byou are\b", "voce e"),
    (r"\byou're\b", "voce e"),
    (r"\byou have\b", "voce tem"),
    (r"\byou've\b", "voce"),
    (r"\byou will\b", "voce vai"),
    (r"\byou'll\b", "voce vai"),
    (r"\byou can\b", "voce pode"),
    (r"\byou can't\b", "voce nao pode"),
    (r"\byou don't\b", "voce nao"),
    (r"\byou didn't\b", "voce nao"),
    (r"\byou need\b", "voce precisa"),
    (r"\byou must\b", "voce deve"),
    (r"\byou should\b", "voce deveria"),
    (r"\byou know\b", "voce sabe"),
    (r"\byou think\b", "voce acha"),
    (r"\byou want\b", "voce quer"),
    (r"\byou look\b", "voce parece"),
    (r"\byou seem\b", "voce parece"),
    (r"\byou were\b", "voce estava"),
    (r"\byour\b", "seu"),
    (r"\byours\b", "seu"),
    (r"\byourself\b", "voce mesmo"),

    (r"\bI am\b", "eu sou"),
    (r"\bI'm\b", "eu sou"),
    (r"\bI was\b", "eu estava"),
    (r"\bI have\b", "eu tenho"),
    (r"\bI've\b", "eu"),
    (r"\bI need\b", "eu preciso"),
    (r"\bI want\b", "eu quero"),
    (r"\bI will\b", "eu vou"),
    (r"\bI'll\b", "eu vou"),
    (r"\bI can\b", "eu posso"),
    (r"\bI can't\b", "eu nao posso"),
    (r"\bI don't\b", "eu nao"),
    (r"\bI didn't\b", "eu nao"),
    (r"\bI know\b", "eu sei"),
    (r"\bI think\b", "eu acho"),
    (r" I ", " eu "),

    (r"\bmy\b", "meu"),
    (r"\bme\b", "me"),
    (r"\bmyself\b", "eu mesmo"),

    (r"\bwe are\b", "nos somos"),
    (r"\bwe're\b", "nos somos"),
    (r"\bwe have\b", "nos temos"),
    (r"\bwe've\b", "nos"),
    (r"\bwe will\b", "nos vamos"),
    (r"\bwe'll\b", "nos vamos"),
    (r"\bwe can\b", "nos podemos"),
    (r"\bwe don't\b", "nos nao"),
    (r"\bwe need\b", "nos precisamos"),
    (r"\bwe must\b", "nos devemos"),
    (r"\bour\b", "nosso"),
    (r"\bours\b", "nosso"),

    (r"\bhe is\b", "ele e"),
    (r"\bhe's\b", "ele e"),
    (r"\bhe was\b", "ele estava"),
    (r"\bhe has\b", "ele tem"),
    (r"\bhe will\b", "ele vai"),
    (r"\bhe'll\b", "ele vai"),
    (r"\bhe can\b", "ele pode"),
    (r"\bhis\b", "dele"),
    (r"\bhim\b", "ele"),
    (r"\bhimself\b", "ele mesmo"),

    (r"\bshe is\b", "ela e"),
    (r"\bshe's\b", "ela e"),
    (r"\bshe was\b", "ela estava"),
    (r"\bshe has\b", "ela tem"),
    (r"\bshe will\b", "ela vai"),
    (r"\bshe'll\b", "ela vai"),
    (r"\bshe can\b", "ela pode"),
    (r"\bher\b", "dela"),
    (r"\bherself\b", "ela mesma"),

    (r"\bthey are\b", "eles sao"),
    (r"\bthey're\b", "eles sao"),
    (r"\bthey have\b", "eles tem"),
    (r"\bthey've\b", "eles"),
    (r"\bthey will\b", "eles vao"),
    (r"\bthey'll\b", "eles vao"),
    (r"\bthey can\b", "eles podem"),
    (r"\bthey don't\b", "eles nao"),
    (r"\btheir\b", "deles"),
    (r"\bthem\b", "eles"),
    (r"\bthemselves\b", "eles mesmos"),

    (r"\bit is\b", "e"),
    (r"\bit's\b", "e"),
    (r"\bit was\b", "era"),
    (r"\bits\b", "seu"),

    (r"\bthere is\b", "ha"),
    (r"\bthere's\b", "ha"),
    (r"\bthere are\b", "ha"),
    (r"\bthere was\b", "havia"),
    (r"\bthere were\b", "havia"),

    # Contractions
    (r"\bdon't\b", "nao"),
    (r"\bdidn't\b", "nao"),
    (r"\bdoesn't\b", "nao"),
    (r"\bcan't\b", "nao pode"),
    (r"\bcannot\b", "nao pode"),
    (r"\bcouldn't\b", "nao podia"),
    (r"\bwon't\b", "nao vai"),
    (r"\bwouldn't\b", "nao iria"),
    (r"\bshouldn't\b", "nao deveria"),
    (r"\bisn't\b", "nao e"),
    (r"\baren't\b", "nao sao"),
    (r"\bwasn't\b", "nao era"),
    (r"\bweren't\b", "nao eram"),
    (r"\bhasn't\b", "nao tem"),
    (r"\bhaven't\b", "nao tem"),
    (r"\bhadn't\b", "nao tinha"),
    (r"\bmustn't\b", "nao deve"),
    (r"\bneedn't\b", "nao precisa"),

    # Common verbs
    (r"\bneed to\b", "precisa"),
    (r"\bwant to\b", "quer"),
    (r"\bhave to\b", "tem que"),
    (r"\bhas to\b", "tem que"),
    (r"\bhad to\b", "teve que"),
    (r"\bable to\b", "capaz de"),
    (r"\bgoing to\b", "vai"),
    (r"\bused to\b", "costumava"),
    (r"\btrying to\b", "tentando"),
    (r"\bwilling to\b", "disposto a"),
    (r"\bready to\b", "pronto para"),
    (r"\bsupposed to\b", "deveria"),
    (r"\bafraid to\b", "com medo de"),
    (r"\bafraid of\b", "com medo de"),
    (r"\bhappy to\b", "feliz em"),
    (r"\bsorry to\b", "desculpe por"),
    (r"\bsorry for\b", "desculpe por"),
    (r"\bsorry about\b", "desculpe por"),
    (r"\bthanks for\b", "obrigado por"),
    (r"\bthank you for\b", "obrigado por"),

    # Common nouns (game terms preserved, general terms translated)
    (r"\badventurer\b", "aventureiro"),
    (r"\bAdventurer\b", "Aventureiro"),
    (r"\badventurers\b", "aventureiros"),
    (r"\btraveler\b", "viajante"),
    (r"\bTraveler\b", "Viajante"),
    (r"\bwarrior\b", "guerreiro"),
    (r"\bWarrior\b", "Guerreiro"),
    (r"\bheroes\b", "herois"),
    (r"\bhero\b", "heroi"),
    (r"\bHero\b", "Heroi"),
    (r"\bvillain\b", "vilao"),
    (r"\bVillain\b", "Vilao"),

    (r"\bmonsters\b", "monstros"),
    (r"\bMonsters\b", "Monstros"),
    (r"\bmonster\b", "monstro"),
    (r"\bMonster\b", "Monstro"),
    (r"\bcreatures\b", "criaturas"),
    (r"\bCreatures\b", "Criaturas"),
    (r"\bcreature\b", "criatura"),
    (r"\bCreature\b", "Criatura"),

    (r"\bkingdom\b", "reino"),
    (r"\bKingdom\b", "Reino"),
    (r"\bvillage\b", "vila"),
    (r"\bVillage\b", "Vila"),
    (r"\btown\b", "cidade"),
    (r"\bTown\b", "Cidade"),
    (r"\bcity\b", "cidade"),
    (r"\bCity\b", "Cidade"),
    (r"\bcastle\b", "castelo"),
    (r"\bCastle\b", "Castelo"),
    (r"\btemple\b", "templo"),
    (r"\bTemple\b", "Templo"),
    (r"\bchurch\b", "igreja"),
    (r"\bChurch\b", "Igreja"),
    (r"\btower\b", "torre"),
    (r"\bTower\b", "Torre"),
    (r"\bforest\b", "floresta"),
    (r"\bForest\b", "Floresta"),
    (r"\bmountain\b", "montanha"),
    (r"\bMountain\b", "Montanha"),
    (r"\bcave\b", "caverna"),
    (r"\bCave\b", "Caverna"),
    (r"\bdungeon\b", "masmorra"),
    (r"\bDungeon\b", "Masmorra"),
    (r"\bisland\b", "ilha"),
    (r"\bIsland\b", "Ilha"),
    (r"\bocean\b", "oceano"),
    (r"\bOcean\b", "Oceano"),
    (r"\bsea\b", "mar"),
    (r"\bSea\b", "Mar"),
    (r"\briver\b", "rio"),
    (r"\bRiver\b", "Rio"),
    (r"\blake\b", "lago"),
    (r"\bLake\b", "Lago"),
    (r"\bdesert\b", "deserto"),
    (r"\bDesert\b", "Deserto"),
    (r"\bswamp\b", "pantano"),
    (r"\bSwamp\b", "Pantano"),
    (r"\bruins\b", "ruinas"),
    (r"\bRuins\b", "Ruinas"),

    (r"\bweapons\b", "armas"),
    (r"\bWeapons\b", "Armas"),
    (r"\bweapon\b", "arma"),
    (r"\bWeapon\b", "Arma"),
    (r"\barmor\b", "armadura"),
    (r"\bArmor\b", "Armadura"),
    (r"\bshield\b", "escudo"),
    (r"\bShield\b", "Escudo"),
    (r"\bswords\b", "espadas"),
    (r"\bSwords\b", "Espadas"),
    (r"\bsword\b", "espada"),
    (r"\bSword\b", "Espada"),
    (r"\bbow\b", "arco"),
    (r"\bBow\b", "Arco"),
    (r"\barrows\b", "flechas"),
    (r"\bArrows\b", "Flechas"),
    (r"\barrow\b", "flecha"),
    (r"\bstaffs?\b", "cajado"),
    (r"\bwand\b", "varinha"),
    (r"\bdagger\b", "adaga"),
    (r"\bDagger\b", "Adaga"),
    (r"\bspear\b", "lanca"),
    (r"\bSpear\b", "Lanca"),
    (r"\baxe\b", "machado"),
    (r"\bAxe\b", "Machado"),
    (r"\bmace\b", "maca"),

    (r"\bpotions\b", "pocoes"),
    (r"\bPotions\b", "Pocoes"),
    (r"\bpotion\b", "pocao"),
    (r"\bPotion\b", "Pocao"),
    (r"\brewards\b", "recompensas"),
    (r"\bRewards\b", "Recompensas"),
    (r"\breward\b", "recompensa"),
    (r"\bReward\b", "Recompensa"),
    (r"\bmoney\b", "dinheiro"),
    (r"\bMoney\b", "Dinheiro"),
    (r"\btreasure\b", "tesouro"),
    (r"\bTreasure\b", "Tesouro"),
    (r"\bgold\b", "ouro"),
    (r"\bGold\b", "Ouro"),
    (r"\bmaterials\b", "materiais"),
    (r"\bMaterials\b", "Materiais"),
    (r"\bmaterial\b", "material"),
    (r"\bequipment\b", "equipamento"),
    (r"\bEquipment\b", "Equipamento"),
    (r"\bitems\b", "itens"),
    (r"\bItems\b", "Itens"),

    (r"\bmagic\b", "magia"),
    (r"\bMagic\b", "Magia"),
    (r"\bspells?\b", "feitico"),
    (r"\bpower\b", "poder"),
    (r"\bPower\b", "Poder"),
    (r"\bpowerful\b", "poderoso"),
    (r"\bPowerful\b", "Poderoso"),
    (r"\bstrength\b", "forca"),
    (r"\bStrength\b", "Forca"),
    (r"\bstronger\b", "mais forte"),
    (r"\bstrong\b", "forte"),
    (r"\bStrong\b", "Forte"),
    (r"\bweaker\b", "mais fraco"),
    (r"\bweak\b", "fraco"),
    (r"\bWeak\b", "Fraco"),
    (r"\bskills\b", "habilidades"),
    (r"\bSkills\b", "Habilidades"),
    (r"\bskill\b", "habilidade"),
    (r"\bSkill\b", "Habilidade"),
    (r"\babilities\b", "habilidades"),
    (r"\bability\b", "habilidade"),
    (r"\bexperience\b", "experiencia"),
    (r"\bExperience\b", "Experiencia"),
    (r"\blevel\b", "nivel"),
    (r"\bLevel\b", "Nivel"),

    (r"\bbattle\b", "batalha"),
    (r"\bBattle\b", "Batalha"),
    (r"\bfight\b", "luta"),
    (r"\bFight\b", "Luta"),
    (r"\bfighting\b", "lutando"),
    (r"\bhunting\b", "cacando"),
    (r"\bHunting\b", "Cacando"),
    (r"\bhunt\b", "cacar"),
    (r"\bHunt\b", "Cacar"),
    (r"\bkill\b", "matar"),
    (r"\bKill\b", "Matar"),
    (r"\bkilled\b", "matou"),
    (r"\bkilling\b", "matando"),
    (r"\bdead\b", "morto"),
    (r"\bDead\b", "Morto"),
    (r"\bdeath\b", "morte"),
    (r"\bDeath\b", "Morte"),
    (r"\bdestroy\b", "destruir"),
    (r"\bDestroy\b", "Destruir"),
    (r"\bdestroyed\b", "destruido"),
    (r"\bdefeat\b", "derrotar"),
    (r"\bDefeated\b", "Derrotado"),
    (r"\bdefeated\b", "derrotado"),
    (r"\battack\b", "atacar"),
    (r"\bAttack\b", "Atacar"),
    (r"\battacked\b", "atacado"),
    (r"\bprotect\b", "proteger"),
    (r"\bProtect\b", "Proteger"),
    (r"\bsave\b", "salvar"),
    (r"\bSave\b", "Salvar"),
    (r"\bsaved\b", "salvou"),
    (r"\brescue\b", "resgatar"),
    (r"\bRescue\b", "Resgatar"),
    (r"\bescape\b", "escapar"),
    (r"\bEscape\b", "Escapar"),

    (r"\bdangerous\b", "perigoso"),
    (r"\bDangerous\b", "Perigoso"),
    (r"\bdanger\b", "perigo"),
    (r"\bDanger\b", "Perigo"),
    (r"\bsafe\b", "seguro"),
    (r"\bSafe\b", "Seguro"),
    (r"\bsafety\b", "seguranca"),
    (r"\bpeace\b", "paz"),
    (r"\bPeace\b", "Paz"),
    (r"\bwar\b", "guerra"),
    (r"\bWar\b", "Guerra"),

    (r"\bancient\b", "antigo"),
    (r"\bAncient\b", "Antigo"),
    (r"\bsacred\b", "sagrado"),
    (r"\bSacred\b", "Sagrado"),
    (r"\bholy\b", "sagrado"),
    (r"\bHoly\b", "Sagrado"),
    (r"\bdark\b", "sombrio"),
    (r"\bDark\b", "Sombrio"),
    (r"\bevil\b", "maligno"),
    (r"\bEvil\b", "Maligno"),
    (r"\bcursed\b", "amaldicoado"),
    (r"\bcurse\b", "maldicao"),
    (r"\bCurse\b", "Maldicao"),
    (r"\blegendary\b", "lendario"),
    (r"\blegend\b", "lenda"),
    (r"\bLegend\b", "Lenda"),
    (r"\bmysterious\b", "misterioso"),
    (r"\bmystery\b", "misterio"),
    (r"\bMystery\b", "Misterio"),
    (r"\bsecret\b", "segredo"),
    (r"\bSecret\b", "Segredo"),
    (r"\btruth\b", "verdade"),
    (r"\bTruth\b", "Verdade"),
    (r"\bstory\b", "historia"),
    (r"\bStory\b", "Historia"),
    (r"\bhistory\b", "historia"),
    (r"\bHistory\b", "Historia"),
    (r"\bdream\b", "sonho"),
    (r"\bDream\b", "Sonho"),
    (r"\bhope\b", "esperanca"),
    (r"\bfear\b", "medo"),
    (r"\bFear\b", "Medo"),
    (r"\bsoul\b", "alma"),
    (r"\bSoul\b", "Alma"),
    (r"\bspirit\b", "espirito"),
    (r"\bSpirit\b", "Espirito"),
    (r"\blife\b", "vida"),
    (r"\bLife\b", "Vida"),
    (r"\bworld\b", "mundo"),
    (r"\bWorld\b", "Mundo"),

    (r"\bpeople\b", "pessoas"),
    (r"\bPeople\b", "Pessoas"),
    (r"\bperson\b", "pessoa"),
    (r"\bchildren\b", "criancas"),
    (r"\bchild\b", "crianca"),
    (r"\bChild\b", "Crianca"),
    (r"\bfamily\b", "familia"),
    (r"\bFamily\b", "Familia"),
    (r"\bfather\b", "pai"),
    (r"\bFather\b", "Pai"),
    (r"\bmother\b", "mae"),
    (r"\bMother\b", "Mae"),
    (r"\bbrother\b", "irmao"),
    (r"\bBrother\b", "Irmao"),
    (r"\bsister\b", "irma"),
    (r"\bSister\b", "Irma"),
    (r"\bson\b", "filho"),
    (r"\bSon\b", "Filho"),
    (r"\bdaughter\b", "filha"),
    (r"\bDaughter\b", "Filha"),
    (r"\bfriends\b", "amigos"),
    (r"\bfriend\b", "amigo"),
    (r"\bFriend\b", "Amigo"),
    (r"\benemies\b", "inimigos"),
    (r"\bEnemy\b", "Inimigo"),
    (r"\benemy\b", "inimigo"),
    (r"\bking\b", "rei"),
    (r"\bKing\b", "Rei"),
    (r"\bqueen\b", "rainha"),
    (r"\bQueen\b", "Rainha"),
    (r"\bprince\b", "principe"),
    (r"\bPrince\b", "Principe"),
    (r"\bprincess\b", "princesa"),
    (r"\bPrincess\b", "Princesa"),
    (r"\bsoldier\b", "soldado"),
    (r"\bSoldier\b", "Soldado"),
    (r"\bsoldiers\b", "soldados"),
    (r"\bguard\b", "guarda"),
    (r"\bGuard\b", "Guarda"),
    (r"\bguards\b", "guardas"),
    (r"\bmerchant\b", "comerciante"),
    (r"\bMerchant\b", "Comerciante"),
    (r"\bpriest\b", "sacerdote"),
    (r"\bPriest\b", "Sacerdote"),
    (r"\bwizard\b", "mago"),
    (r"\bWizard\b", "Mago"),
    (r"\bthief\b", "ladrao"),
    (r"\bThief\b", "Ladrao"),
    (r"\bassassin\b", "assassino"),
    (r"\bAssassin\b", "Assassino"),
    (r"\bsage\b", "sabio"),
    (r"\bSage\b", "Sabio"),

    # Time
    (r"\btoday\b", "hoje"),
    (r"\bToday\b", "Hoje"),
    (r"\btomorrow\b", "amanha"),
    (r"\bTomorrow\b", "Amanha"),
    (r"\byesterday\b", "ontem"),
    (r"\bYesterday\b", "Ontem"),
    (r"\bnow\b", "agora"),
    (r"\bNow\b", "Agora"),
    (r"\bsoon\b", "em breve"),
    (r"\blater\b", "depois"),
    (r"\balways\b", "sempre"),
    (r"\bnever\b", "nunca"),
    (r"\bNever\b", "Nunca"),
    (r"\bsometimes\b", "as vezes"),
    (r"\bagain\b", "novamente"),
    (r"\bforever\b", "para sempre"),
    (r"\blong ago\b", "ha muito tempo"),
    (r"\blong time\b", "muito tempo"),

    # Adjectives
    (r"\bbeautiful\b", "belo"),
    (r"\bBeautiful\b", "Belo"),
    (r"\bwonderful\b", "maravilhoso"),
    (r"\bterrible\b", "terrivel"),
    (r"\bhorrible\b", "horrivel"),
    (r"\bstrange\b", "estranho"),
    (r"\bStrange\b", "Estranho"),
    (r"\bfamous\b", "famoso"),
    (r"\bimportant\b", "importante"),
    (r"\bImportant\b", "Importante"),
    (r"\bnecessary\b", "necessario"),
    (r"\bimpossible\b", "impossivel"),
    (r"\bpossible\b", "possivel"),
    (r"\bdifficult\b", "dificil"),
    (r"\bDifficult\b", "Dificil"),
    (r"\beasy\b", "facil"),
    (r"\bEasy\b", "Facil"),
    (r"\bhappy\b", "feliz"),
    (r"\bHappy\b", "Feliz"),
    (r"\bsad\b", "triste"),
    (r"\bangry\b", "furioso"),
    (r"\bafraid\b", "com medo"),
    (r"\bbrave\b", "corajoso"),
    (r"\bBrave\b", "Corajoso"),
    (r"\bwise\b", "sabio"),
    (r"\bWise\b", "Sabio"),

    # Common words
    (r"\beveryone\b", "todos"),
    (r"\bEveryone\b", "Todos"),
    (r"\beverything\b", "tudo"),
    (r"\bEverything\b", "Tudo"),
    (r"\bsomething\b", "algo"),
    (r"\bSomething\b", "Algo"),
    (r"\bsomeone\b", "alguem"),
    (r"\bSomeone\b", "Alguem"),
    (r"\bnothing\b", "nada"),
    (r"\bNothing\b", "Nada"),
    (r"\bnobody\b", "ninguem"),
    (r"\bNobody\b", "Ninguem"),
    (r"\banywhere\b", "qualquer lugar"),
    (r"\beverywhere\b", "em todo lugar"),
    (r"\bnowhere\b", "em nenhum lugar"),
    (r"\bhere\b", "aqui"),
    (r"\bHere\b", "Aqui"),
    (r"\bthere\b", "la"),
    (r"\bvery\b", "muito"),
    (r"\bmuch\b", "muito"),
    (r"\bmany\b", "muitos"),
    (r"\bMany\b", "Muitos"),
    (r"\bfew\b", "poucos"),
    (r"\benough\b", "suficiente"),
    (r"\bonly\b", "apenas"),
    (r"\bjust\b", "apenas"),
    (r"\balso\b", "tambem"),
    (r"\btoo\b", "tambem"),
    (r"\bmaybe\b", "talvez"),
    (r"\bperhaps\b", "talvez"),
    (r"\breally\b", "realmente"),
    (r"\bactually\b", "na verdade"),
    (r"\bcertainly\b", "certamente"),
    (r"\bprobably\b", "provavelmente"),
    (r"\bdefinitely\b", "definitivamente"),
    (r"\bsurely\b", "certamente"),
    (r"\bfinally\b", "finalmente"),
    (r"\bFinally\b", "Finalmente"),
    (r"\balready\b", "ja"),
    (r"\bstill\b", "ainda"),
    (r"\beven\b", "ate"),
    (r"\byet\b", "ainda"),

    # Prepositions and connectors
    (r"\bbecause\b", "porque"),
    (r"\bbut\b", "mas"),
    (r"\band\b", "e"),
    (r"\bor\b", "ou"),
    (r"\bwith\b", "com"),
    (r"\bwithout\b", "sem"),
    (r"\babout\b", "sobre"),
    (r"\bbefore\b", "antes"),
    (r"\bafter\b", "depois"),
    (r"\bduring\b", "durante"),
    (r"\buntil\b", "ate"),
    (r"\bsince\b", "desde"),
    (r"\bwhile\b", "enquanto"),
    (r"\bthrough\b", "atraves"),
    (r"\bbetween\b", "entre"),
    (r"\bagainst\b", "contra"),
    (r"\baround\b", "ao redor"),
    (r"\bbehind\b", "atras"),
    (r"\bnear\b", "perto"),
    (r"\binside\b", "dentro"),
    (r"\boutside\b", "fora"),
    (r"\bunder\b", "embaixo"),
    (r"\bover\b", "sobre"),
    (r"\babove\b", "acima"),
    (r"\bbelow\b", "abaixo"),

    # Common verbs
    (r"\bknow\b", "saber"),
    (r"\bknew\b", "sabia"),
    (r"\bknown\b", "conhecido"),
    (r"\bthink\b", "achar"),
    (r"\bthought\b", "pensou"),
    (r"\bbelieve\b", "acreditar"),
    (r"\bremember\b", "lembrar"),
    (r"\bforget\b", "esquecer"),
    (r"\bforgot\b", "esqueceu"),
    (r"\bforgotten\b", "esquecido"),
    (r"\bunderstand\b", "entender"),
    (r"\bunderstood\b", "entendeu"),
    (r"\bhear\b", "ouvir"),
    (r"\bheard\b", "ouviu"),
    (r"\bsee\b", "ver"),
    (r"\bsaw\b", "viu"),
    (r"\bseen\b", "visto"),
    (r"\blook\b", "olhar"),
    (r"\blooked\b", "olhou"),
    (r"\blooking\b", "olhando"),
    (r"\bfind\b", "encontrar"),
    (r"\bfound\b", "encontrou"),
    (r"\bsearch\b", "procurar"),
    (r"\bsearching\b", "procurando"),
    (r"\bgive\b", "dar"),
    (r"\bgave\b", "deu"),
    (r"\bgiven\b", "dado"),
    (r"\btake\b", "pegar"),
    (r"\btook\b", "pegou"),
    (r"\btaken\b", "pego"),
    (r"\bbring\b", "trazer"),
    (r"\bbrought\b", "trouxe"),
    (r"\bcome\b", "vir"),
    (r"\bcame\b", "veio"),
    (r"\bgo\b", "ir"),
    (r"\bgone\b", "ido"),
    (r"\bwent\b", "foi"),
    (r"\bget\b", "conseguir"),
    (r"\bgot\b", "conseguiu"),
    (r"\bmake\b", "fazer"),
    (r"\bmade\b", "fez"),
    (r"\bmaking\b", "fazendo"),
    (r"\buse\b", "usar"),
    (r"\bused\b", "usado"),
    (r"\busing\b", "usando"),
    (r"\bkeep\b", "manter"),
    (r"\bkept\b", "manteve"),
    (r"\bput\b", "colocar"),
    (r"\bsend\b", "enviar"),
    (r"\bsent\b", "enviou"),
    (r"\btell\b", "dizer"),
    (r"\btold\b", "disse"),
    (r"\bsay\b", "dizer"),
    (r"\bsaid\b", "disse"),
    (r"\bsaying\b", "dizendo"),
    (r"\bspeak\b", "falar"),
    (r"\bspoke\b", "falou"),
    (r"\bspoken\b", "falado"),
    (r"\btalk\b", "falar"),
    (r"\btalking\b", "falando"),
    (r"\bask\b", "perguntar"),
    (r"\basked\b", "perguntou"),
    (r"\basking\b", "perguntando"),
    (r"\banswer\b", "responder"),
    (r"\banswered\b", "respondeu"),
    (r"\bwait\b", "esperar"),
    (r"\bwaiting\b", "esperando"),
    (r"\bhelp\b", "ajudar"),
    (r"\bhelped\b", "ajudou"),
    (r"\bhelping\b", "ajudando"),
    (r"\bneed\b", "precisar"),
    (r"\bneeded\b", "precisou"),
    (r"\bwant\b", "querer"),
    (r"\bwanted\b", "queria"),
    (r"\btry\b", "tentar"),
    (r"\btried\b", "tentou"),
    (r"\btrying\b", "tentando"),
    (r"\bwork\b", "trabalhar"),
    (r"\bworked\b", "trabalhou"),
    (r"\bworking\b", "trabalhando"),
    (r"\blearn\b", "aprender"),
    (r"\blearned\b", "aprendeu"),
    (r"\bteach\b", "ensinar"),
    (r"\btaught\b", "ensinou"),
    (r"\bcreate\b", "criar"),
    (r"\bcreated\b", "criou"),
    (r"\bbuild\b", "construir"),
    (r"\bbuilt\b", "construiu"),
    (r"\bopen\b", "abrir"),
    (r"\bopened\b", "abriu"),
    (r"\bclose\b", "fechar"),
    (r"\bclosed\b", "fechou"),
    (r"\bread\b", "ler"),
    (r"\bwrite\b", "escrever"),
    (r"\bwritten\b", "escrito"),
    (r"\blive\b", "viver"),
    (r"\blived\b", "viveu"),
    (r"\bliving\b", "vivendo"),
    (r"\bdie\b", "morrer"),
    (r"\bdied\b", "morreu"),
    (r"\bdying\b", "morrendo"),
    (r"\brun\b", "correr"),
    (r"\brunning\b", "correndo"),
    (r"\bwalk\b", "andar"),
    (r"\bwalking\b", "andando"),
    (r"\bstand\b", "ficar de pe"),
    (r"\bstanding\b", "de pe"),
    (r"\bsit\b", "sentar"),
    (r"\bsitting\b", "sentado"),
    (r"\bsleep\b", "dormir"),
    (r"\bsleeping\b", "dormindo"),
    (r"\beat\b", "comer"),
    (r"\beating\b", "comendo"),
    (r"\bdrink\b", "beber"),
    (r"\bdrinking\b", "bebendo"),
    (r"\bbuy\b", "comprar"),
    (r"\bbought\b", "comprou"),
    (r"\bsell\b", "vender"),
    (r"\bsold\b", "vendeu"),
    (r"\bpay\b", "pagar"),
    (r"\bpaid\b", "pagou"),
    (r"\bsteal\b", "roubar"),
    (r"\bstole\b", "roubou"),
    (r"\bstolen\b", "roubado"),
    (r"\bcollect\b", "coletar"),
    (r"\bcollected\b", "coletou"),
    (r"\bcollecting\b", "coletando"),
    (r"\bgather\b", "juntar"),
    (r"\bgathered\b", "juntou"),
    (r"\bgathering\b", "juntando"),
    (r"\breturn\b", "retornar"),
    (r"\breturned\b", "retornou"),
    (r"\breturning\b", "retornando"),
    (r"\bvisit\b", "visitar"),
    (r"\bvisited\b", "visitou"),
    (r"\btravel\b", "viajar"),
    (r"\btraveling\b", "viajando"),
    (r"\bmove\b", "mover"),
    (r"\bmoving\b", "movendo"),
    (r"\bfollow\b", "seguir"),
    (r"\bfollowing\b", "seguindo"),
    (r"\bfollowed\b", "seguiu"),
    (r"\bhide\b", "esconder"),
    (r"\bhidden\b", "escondido"),
    (r"\bhiding\b", "escondendo"),
    (r"\bchange\b", "mudar"),
    (r"\bchanged\b", "mudou"),
    (r"\bchanging\b", "mudando"),
    (r"\bprepare\b", "preparar"),
    (r"\bprepared\b", "preparou"),
    (r"\bstart\b", "comecar"),
    (r"\bstarted\b", "comecou"),
    (r"\bstarting\b", "comecando"),
    (r"\bfinish\b", "terminar"),
    (r"\bfinished\b", "terminou"),
    (r"\bcomplete\b", "completar"),
    (r"\bcompleted\b", "completou"),
    (r"\baccept\b", "aceitar"),
    (r"\baccepted\b", "aceitou"),
    (r"\brefuse\b", "recusar"),
    (r"\brefused\b", "recusou"),
    (r"\bchoose\b", "escolher"),
    (r"\bchose\b", "escolheu"),
    (r"\bchosen\b", "escolhido"),
    (r"\bdecide\b", "decidir"),
    (r"\bdecided\b", "decidiu"),
    (r"\bexplain\b", "explicar"),
    (r"\bexplained\b", "explicou"),
    (r"\bpromise\b", "prometer"),
    (r"\bpromised\b", "prometeu"),
    (r"\bwarn\b", "avisar"),
    (r"\bwarned\b", "avisou"),
    (r"\btrust\b", "confiar"),
    (r"\btrusted\b", "confiou"),
    (r"\bbetray\b", "trair"),
    (r"\bbetrayed\b", "traiu"),

    # Articles and small words (be very careful with these)
    (r"\bthe\b", "o"),
    (r"\bThe\b", "O"),
    (r"\ba\b", "um"),
    (r"\ban\b", "um"),
    (r"\bthis\b", "isso"),
    (r"\bThis\b", "Isso"),
    (r"\bthat\b", "isso"),
    (r"\bThat\b", "Isso"),
    (r"\bthese\b", "esses"),
    (r"\bThese\b", "Esses"),
    (r"\bthose\b", "aqueles"),
    (r"\bThose\b", "Aqueles"),
    (r"\bwhich\b", "que"),
    (r"\bwho\b", "quem"),
    (r"\bWho\b", "Quem"),
    (r"\bwhat\b", "o que"),
    (r"\bwhere\b", "onde"),
    (r"\bWhere\b", "Onde"),
    (r"\bwhen\b", "quando"),
    (r"\bWhen\b", "Quando"),
    (r"\bhow\b", "como"),
    (r"\bHow\b", "Como"),
    (r"\bwhy\b", "por que"),
    (r"\bWhy\b", "Por que"),

    (r"\bfrom\b", "de"),
    (r"\bFrom\b", "De"),
    (r"\binto\b", "em"),
    (r"\bfor\b", "para"),
    (r"\bFor\b", "Para"),
    (r"\bto\b", "para"),
    (r"\bTo\b", "Para"),
    (r"\bin\b", "em"),
    (r"\bIn\b", "Em"),
    (r"\bat\b", "em"),
    (r"\bAt\b", "Em"),
    (r"\bon\b", "em"),
    (r"\bOn\b", "Em"),
    (r"\bby\b", "por"),
    (r"\bBy\b", "Por"),
    (r"\bof\b", "de"),
    (r"\bOf\b", "De"),
    (r"\bas\b", "como"),
    (r"\bAs\b", "Como"),
    (r"\bso\b", "entao"),
    (r"\bthen\b", "entao"),
    (r"\bif\b", "se"),
    (r"\bnot\b", "nao"),
    (r"\bNot\b", "Nao"),
    (r"\bno\b", "nao"),
    (r"\bNo\b", "Nao"),
    (r"\byes\b", "sim"),
    (r"\bYes\b", "Sim"),
    (r"\bok\b", "ok"),
    (r"\bOk\b", "Ok"),
    (r"\bokay\b", "ok"),
    (r"\bOkay\b", "Ok"),
]

# Compile patterns
COMPILED_PATTERNS = [(re.compile(p, re.IGNORECASE if p.startswith('^') and p[1].isupper() else 0), r) for p, r in PHRASE_PATTERNS]

# Select menu translations - common patterns
SELECT_PATTERNS = [
    (r"\bYes\b", "Sim"),
    (r"\bNo\b", "Nao"),
    (r"\bCancel\b", "Cancelar"),
    (r"\bQuit\b", "Desistir"),
    (r"\bContinue\b", "Continuar"),
    (r"\bAccept\b", "Aceitar"),
    (r"\bRefuse\b", "Recusar"),
    (r"\bAgree\b", "Concordar"),
    (r"\bDisagree\b", "Discordar"),
    (r"\bHelp\b", "Ajudar"),
    (r"\bLeave\b", "Sair"),
    (r"\bStay\b", "Ficar"),
    (r"\bSure\b", "Claro"),
    (r"\bOK\b", "OK"),
    (r"\bOkay\b", "Ok"),
    (r"\bWait\b", "Esperar"),
    (r"\bI want to quit\b", "Quero desistir"),
    (r"\bI'll do it\b", "Eu faco"),
    (r"\bI'll help\b", "Eu ajudo"),
    (r"\bTell me more\b", "Me conte mais"),
    (r"\bNever mind\b", "Deixa pra la"),
    (r"\bNevermind\b", "Deixa pra la"),
    (r"\bNot yet\b", "Ainda nao"),
    (r"\bNot now\b", "Agora nao"),
    (r"\bMaybe later\b", "Talvez depois"),
    (r"\bGo ahead\b", "Va em frente"),
    (r"\bI see\b", "Entendo"),
    (r"\bI understand\b", "Entendo"),
    (r"\bI don't know\b", "Nao sei"),
    (r"\bI don't care\b", "Nao me importo"),
    (r"\bI'll think about it\b", "Vou pensar"),
    (r"\bWhat\?\b", "O que?"),
    (r"\bWhat is it\?\b", "O que e?"),
    (r"\bGather Items\b", "Coletar Itens"),
    (r"\bCollect Items\b", "Coletar Itens"),
    (r"\bHunt\b", "Cacar"),
    (r"\bStop\b", "Parar"),
    (r"\bThanks\b", "Obrigado"),
    (r"\bThank you\b", "Obrigado"),
    (r"\bGoodbye\b", "Adeus"),
    (r"\bFarewell\b", "Adeus"),
    (r"\bSorry\b", "Desculpe"),
    (r"\bOf course\b", "Claro"),
    (r"\bPlease\b", "Por favor"),
    (r"\bI have\b", "Eu tenho"),
    (r"\bI don't have\b", "Nao tenho"),
    (r"\bI need\b", "Preciso"),
    (r"\bNext\b", "Proximo"),
    (r"\bBack\b", "Voltar"),
    (r"\bRepeat\b", "Repetir"),
    (r"\bAsk again\b", "Perguntar de novo"),
    (r"\bLet me think\b", "Deixe-me pensar"),
    (r"\bThat's right\b", "Isso mesmo"),
    (r"\bNo thanks\b", "Nao, obrigado"),
    (r"\bNo, thanks\b", "Nao, obrigado"),
    (r"\bNothing\b", "Nada"),
]

COMPILED_SELECT_PATTERNS = [(re.compile(p), r) for p, r in SELECT_PATTERNS]


def is_portuguese(text):
    """Check if text already appears to be in Portuguese."""
    pt_markers = ['voce', 'nao ', 'entao', 'tambem', 'porque', 'agora',
                  'ainda', 'preciso', 'obrigado', 'Cancelar', 'certeza',
                  'recompensa', 'gostaria', 'terminou', 'cacando', 'cacar',
                  'Lembre', 'ideia', 'progresso', 'apagado', 'mudar',
                  'Coletar', 'tarefa', 'Espero', 'criadores', 'jacare',
                  'poderoso', 'corajoso', 'Incrivel', 'Otimo', 'Desculpe',
                  'Volte', 'Onde', 'Aqui', 'Acho', 'Saudacoes', 'Ola,',
                  'Bom dia', 'Boa noite', 'Boa tarde', 'Bem-vindo',
                  'Adeus', 'Cuide-se', 'Boa sorte', 'Serio', 'Impossivel',
                  'Excelente', 'Perfeito', 'Maravilhoso', 'Interessante',
                  'Entendo', 'Com certeza', 'Exatamente', 'De fato',
                  'Quem e', 'O que', 'Como posso', 'Tem certeza',
                  'Espere', 'Tenha cuidado', 'Nao se preocupe',
                  'Nao esqueca', 'Ate mais', 'Va embora', 'Saia',
                  'Va em frente', 'Siga-me', 'Me escute', 'Olhe',
                  'Traga', 'Me de', 'Me ajude', 'Voce e', 'Voce pode',
                  'Voce precisa', 'Voce deve', 'Voce vai', 'Voce sabe',
                  'Voce parece', 'Voce quer', 'Voce acha', 'Voce tem',
                  'Eu sou', 'Eu tenho', 'Eu preciso', 'Eu quero',
                  'Eu vou', 'Eu posso', 'Eu sei', 'Eu acho',
                  'Eu acredito', 'Eu espero', 'Eu lembro', 'Eu ouvi',
                  'Nos somos', 'Nos temos', 'Nos precisamos',
                  'Ele e', 'Ela e', 'Eles sao',
                  'Ha ', 'Havia', 'Isso e', 'Esses sao',
                  'Por favor', 'Deixe-me', 'Vamos', 'Venha',
                  'Porem', 'Mas ', 'Entao', 'Tambem', 'Na verdade',
                  'Embora', 'Mesmo', 'Talvez', 'Porque',
                  'monstro', 'aventureiro', 'guerreiro', 'viajante',
                  'Suspiro', 'duvidas', 'Parece', 'Sim,', 'Nao,',
                  'livrou', 'livre-se']
    for m in pt_markers:
        if m in text:
            return True
    return False


def translate_mes_content(text):
    """Translate mes dialogue content from English to Portuguese."""
    # Skip NPC name lines
    if re.match(r'^\[.*\]$', text.strip()):
        return text

    # Skip empty or very short
    if len(text.strip()) < 2:
        return text

    # Skip if already in Portuguese
    if is_portuguese(text):
        return text

    # Skip if it's just color codes/formatting with no real text
    stripped = re.sub(r'\^[0-9A-Fa-f]{6}', '', text)
    if not re.search(r'[a-zA-Z]{3,}', stripped):
        return text

    result = text
    for pattern, replacement in COMPILED_PATTERNS:
        result = pattern.sub(replacement, result)

    return result


def translate_select_content(text):
    """Translate select menu options from English to Portuguese."""
    if is_portuguese(text):
        return text

    # Split by : to handle each option
    options = text.split(':')
    translated = []
    for opt in options:
        result = opt
        for pattern, replacement in COMPILED_SELECT_PATTERNS:
            result = pattern.sub(replacement, result)
        translated.append(result)
    return ':'.join(translated)


def process_file(filepath):
    """Process a single file, translating mes and select content."""
    with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
        content = f.read()

    original = content
    lines = content.split('\n')
    new_lines = []

    for line in lines:
        new_line = line

        # Process mes "..." lines
        m = re.match(r'^(\s*mes\s+")(.*)(";.*)$', line)
        if m:
            prefix, text, suffix = m.group(1), m.group(2), m.group(3)
            translated = translate_mes_content(text)
            new_line = prefix + translated + suffix

        # Process select("...") patterns
        sm = re.search(r'(select\(")([^"]+)("\))', line)
        if sm:
            sel_text = sm.group(2)
            translated_sel = translate_select_content(sel_text)
            new_line = new_line[:sm.start()] + sm.group(1) + translated_sel + sm.group(3) + new_line[sm.end():]

        new_lines.append(new_line)

    new_content = '\n'.join(new_lines)

    if new_content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(new_content)
        return True
    return False


def main():
    dirs_to_process = [
        os.path.join(BASE, "npc", "quests"),
        os.path.join(BASE, "npc", "pre-re", "quests"),
    ]

    count = 0
    total = 0

    for base_dir in dirs_to_process:
        for root, dirs, files in os.walk(base_dir):
            for fn in sorted(files):
                if fn.endswith('.txt'):
                    fp = os.path.join(root, fn)
                    total += 1
                    if process_file(fp):
                        count += 1
                        print(f"Translated: {os.path.relpath(fp, BASE)}")
                    else:
                        print(f"No changes: {os.path.relpath(fp, BASE)}")

    print(f"\nTotal files processed: {total}")
    print(f"Files translated: {count}")


if __name__ == '__main__':
    main()
