import os
import re

def translate_file(filepath, replacements):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    for old, new in replacements:
        content = content.replace(old, new)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Updated: {filepath}")

# === VEINS ===
veins_r = []

# Veins NPC dialogue - translate ALL remaining English mes lines
# We'll do broad pattern replacements
veins_content_replacements = [
    # Towner#ve1 - cactus lover
    ('mes "I love cacti. They', 'mes "Eu amo cactos. Eles'),
    ('the most bonito plants', 'as plantas mais bonitas'),
    ('in the desert. Sometimes,', 'do deserto. As vezes,'),
    ("they're the only signs of", 'eles sao os unicos sinais de'),
    ('life in a barren land.', 'vida em uma terra arida.'),
    ('If you feel a stirring', 'Se voce sentir uma emocao'),
    ('in your heart when you', 'no seu coracao quando'),
    ('look at a cactus, you', 'olhar para um cacto, voce'),
    ('must appreciate the', 'deve apreciar a'),
    ("desert's true beauty.", 'verdadeira beleza do deserto.'),
    ("Well, I don't know if", 'Bom, nao sei se'),
    ('I can find anyone that', 'consigo encontrar alguem que'),
    ('finds the desert as', 'ache o deserto tao'),
    ('wonderful and enchanting', 'maravilhoso e encantador'),
    ("as I do. It's a pity, really.", 'quanto eu. E uma pena, de verdade.'),
    # Towner#ve2
    ('town near the Temple of', 'cidade perto do Templo de'),
    ('Cheshrumnir. You may think', 'Cheshrumnir. Voce pode achar'),
    ('this is a dreary desert town,', 'que e uma cidade deserta e sombria,'),
    ("but you'll find that it's as", 'mas vai descobrir que e tao'),
    ('lively as any other place.', 'animada quanto qualquer outro lugar.'),
    ('Sure, there are a few', 'Claro, tem uns poucos'),
    ('characters in town, like', 'personagens na cidade, como'),
    ('that cactus loving loony', 'aquele maluco amante de cactos'),
    ("over there, but not everyone's", 'ali, mas nem todo mundo e'),
    ("like him. There's lots of nice,", 'como ele. Tem muitas pessoas legais,'),
    ('kind people that you can meet.', 'gentis que voce pode conhecer.'),
    ('Well then, I hope that', 'Bom, espero que'),
    ('you enjoy your stay~', 'voce aproveite sua estadia~'),
    # Towner#ve3 - weapon shop
    ('Geez, why is our weapon', 'Puxa, por que nossa loja'),
    ('shop so boring? Nothing', 'de armas e tao chata? Nada'),
    ("there but the same ol'", 'la alem das mesmas'),
    ('regular junk. Sad to say,', 'tranqueiras de sempre. Triste dizer,'),
    ("there's nothing special.", 'nao tem nada de especial.'),
    ("Wouldn't it be great", 'Nao seria otimo'),
    ('if there was a shop that', 'se houvesse uma loja que'),
    ('sold the legendary godly', 'vendesse as lendarias armas'),
    # Towner#ve4
    ("Though we're in the", 'Embora estejamos no'),
    ('middle of the desert,', 'meio do deserto,'),
    ('our enemies continue', 'nossos inimigos continuam'),
    ('to threaten us. Fools!', 'a nos ameacar. Tolos!'),
    ('Goddess Freya will', 'A Deusa Freya sempre'),
    ('always protect us!', 'nos protegera!'),
    ('So long as we continue to', 'Enquanto continuarmos a'),
    ('train, Freya will watch over', 'treinar, Freya cuidara de'),
    ('us and bless us with victory', 'nos e nos abencoara com vitoria'),
    ('over our foes. That, friend,', 'sobre nossos inimigos. Isso, amigo,'),
    ('is the power of faith.', 'e o poder da fe.'),
    # Kid#ve1
    ('Whoa, get out of here!', 'Ei, sai daqui!'),
    ("Can't you see that I'm", 'Nao ve que eu estou'),
    ('playing hide and go seek?!', 'brincando de esconde-esconde?!'),
    ('Move before they find me!', 'Sai antes que me encontrem!'),
    # Kid#ve2
    ('Gosh, where could she', 'Puxa, onde ela pode'),
    ("be hiding? I hate being", 'estar escondida? Odeio ser'),
    ("it... There's so many places", 'o pegador... Tem tantos lugares'),
    ('to hide around here. There', 'pra se esconder por aqui. Deve'),
    ("must be someplace I haven't", 'ter algum lugar que eu nao'),
    ("checked yet... Let's see...", 'verifiquei ainda... Deixa eu ver...'),
    # Old Man#ve1
    ('Praise be to Freya', 'Louvada seja Freya'),
    ('for blessing me with', 'por me abencoar com'),
    ('long life, but I wonder', 'longa vida, mas eu me pergunto'),
    ("if I've fully lived life.", 'se eu vivi a vida plenamente.'),
    ("I don't have any regrets", 'Nao tenho nenhum arrependimento'),
    ('or doubts, but maybe there', 'ou duvida, mas talvez existam'),
    ('are a few things I missed', 'algumas coisas que eu perdi'),
    ('out on. I guess an old man', 'por ai. Acho que um velho'),
    ("can't help but think about", 'nao pode deixar de pensar'),
    ('these sorts of things...', 'nesse tipo de coisa...'),
    # Towner#ve5
    ('Cacti are wonderful,', 'Cactos sao maravilhosos,'),
    ("they're the most bonito", 'eles sao as mais bonitas'),
    ('plants in the desert. Yes, we', 'plantas do deserto. Sim, nos'),
    ('must cherish and nurture them~', 'devemos cuidar e nutri-los~'),
    ('Regular cacti are ', 'Cactos normais sao '),
    ('pretty uncommon, but', 'bem incomuns, mas'),
    ("I hear there's a kind of", 'ouvi dizer que ha um tipo de'),
    ('cactus that roams the desert', 'cacto que vaga pelo deserto'),
    ('and makes loud, obnoxious', 'e faz barulhos altos e irritantes.'),
    ('noises. How can that be true?', 'Como isso pode ser verdade?'),
    # Towner#ve6
    ('What do you want?', 'O que voce quer?'),
    ("Sorry, but I'm just", 'Desculpe, mas eu sou apenas'),
    ('a normal guy with normal', 'um cara normal com problemas'),
    ('problems. Nothing that', 'normais. Nada que'),
    ("I can't solve on my own.", 'eu nao possa resolver sozinho.'),
    ('Unless... You can do my', 'A menos que... Voce pode fazer meu'),
    ('taxes? Pay off my mortgage?', 'imposto? Pagar minha hipoteca?'),
    ("No? Heh. Didn't think so.", 'Nao? Heh. Ja imaginava.'),
    # Towner#ve7
    ("What's an aventureiro", 'O que um aventureiro'),
    ('doing here in such an', 'esta fazendo aqui em uma'),
    ('isolated, dreary town?', 'cidade tao isolada e sombria?'),
    ("Shouldn't you be looking", 'Voce nao deveria estar procurando'),
    ('for adventures? Take it from', 'por aventuras? Acredite em mim,'),
    ('me, this place if bo-ring.', 'esse lugar e cha-to.'),
    # Towner#ve8
    ("Whoa, it's been a while", 'Uau, faz um tempo'),
    ("seen I've seen tourists", 'que nao vejo turistas'),
    ('in town. You might think', 'na cidade. Voce pode achar'),
    ("there's nothing here, but", 'que nao tem nada aqui, mas'),
    ('take a closer look. You', 'olhe mais de perto. Voce'),
    ('might learn something.', 'pode aprender algo.'),
    ('Just like people, you', 'Assim como pessoas, voce'),
    ("can't know everything about", 'nao pode saber tudo sobre'),
    ('a place with only a glance.', 'um lugar com apenas um olhar.'),
    ("If you give it a chance, I'm", "Se voce der uma chance, tenho"),
    ("sure you'll find something", 'certeza que vai encontrar algo'),
    ('to like about this town.', 'pra gostar nesta cidade.'),
    ('and try to find things that mind interest you?', 'e tente encontrar coisas que possam te interessar?'),
    ("What do I mean by ''a", "O que eu quero dizer com ''um"),
    ("closer look?'' Heh, you'll", "olhar mais de perto''? Heh, voce"),
    ("see... Maybe. Hahahaha!", 'vai ver... Talvez. Hahahaha!'),
    ("Oh, forget it, it's not", 'Ah, esquece, nao e'),
    ('that important anyway.', 'tao importante assim.'),
    ('May Freya bless you~', 'Que Freya te abencoe~'),
    # Kid#ve3
    ('I really want to look', 'Eu realmente quero olhar'),
    ('inside the temple, but', 'dentro do templo, mas'),
    ('it looks so scary from', 'parece tao assustador de'),
    ('the outside! I wonder', 'fora! Eu me pergunto'),
    ("why it's like that?", 'por que e assim?'),
    # Towner#ve9
    ("Don't get me wrong:", 'Nao me entenda mal:'),
    ("I'd give my life in Freya's", 'Eu daria minha vida em nome de'),
    ('name, but that so-called', 'Freya, mas esse tal'),
    ('temple just looks so strange', 'templo parece tao estranho'),
    ('and suspicious. How can it', 'e suspeito. Como pode'),
    ('be a place of worship?', 'ser um lugar de adoracao?'),
    # Towner#ve10
    ('I guess you can tell', 'Acho que da pra perceber'),
    ('from this withered tree', 'por essa arvore murcha'),
    ('that our town is short', 'que nossa cidade esta com'),
    ("on water. I guess that's", 'falta de agua. Acho que essa e'),
    ('a natural consequence of', 'uma consequencia natural de'),
    ('living here in the desert...', 'viver aqui no deserto...'),
    # Old lady#ve1
    ('When I look down on', 'Quando eu olho pra baixo em'),
    ("Veins from here, I've", 'Veins daqui, eu acabei'),
    ('come to realize many things.', 'percebendo muitas coisas.'),
    ("I don't think you'd understand", 'Nao acho que voce entenderia'),
    ('no matter how much I explained.', 'nao importa o quanto eu explicasse.'),
    ("I suppose it's one of those", 'Eu acho que e uma daquelas'),
    ('things that you learn with age.', 'coisas que voce aprende com a idade.'),
    ("Yes, there's no substitute for", 'Sim, nao ha substituto para'),
    ('experience when it comes to', 'a experiencia quando se trata de'),
    ("some things. You'll see.", 'algumas coisas. Voce vai ver.'),
    ('^FFFFFFYes, like secret knowledge.^000000', '^FFFFFFSim, como conhecimento secreto.^000000'),
    # Old Man#ve2
    ("This isn't good.", 'Isso nao e bom.'),
    ('The elderly outnumber', 'Os idosos superam em numero'),
    ('the youth here in Veins.', 'os jovens aqui em Veins.'),
    ("We're too close to becoming", 'Estamos muito perto de nos tornar'),
    ('something of a retirement', 'algo como uma comunidade'),
    ('community. You see it, right?', 'de aposentados. Voce ve isso, ne?'),
    ('I guess the young people', 'Acho que os jovens'),
    ("aren't content living here", 'nao estao contentes morando aqui'),
    ("since we lack a lot of the", 'ja que nos falta muito da'),
    ('material excitement of other', 'empolgacao material de outras'),
    ("towns. They can't appreciate", 'cidades. Eles nao conseguem apreciar'),
    ("what's really special here...", 'o que e realmente especial aqui...'),
    # Towner#ve11
    ('People cherish water', 'As pessoas valorizam a agua'),
    ("around here, but I've", 'por aqui, mas eu tenho'),
    ('something even more', 'algo ainda mais'),
    ('precious to me. Yes, even', 'precioso pra mim. Sim, ainda'),
    ('more precious than water...', 'mais precioso que agua...'),
    ('You guessed it--true love.', 'Voce adivinhou--amor verdadeiro.'),
    ('We actually started dating', 'Na verdade comecamos a namorar'),
    ('here, so this place really', 'aqui, entao esse lugar realmente'),
    ("means a lot to me. It's my", 'significa muito pra mim. E meu'),
    ('favorite spot for spending', 'lugar favorito pra passar'),
    ('time with my girl. Hahaha~', 'tempo com minha garota. Hahaha~'),
    # Towner#ve12
    ("Well, I'm actually", 'Bom, na verdade estou'),
    ('a little tired of coming', 'um pouco cansada de vir'),
    ('here all the time. I kind', 'aqui o tempo todo. Eu meio'),
    ('of want to try someplace', 'que quero tentar outro'),
    ('else, but I also know he', 'lugar, mas eu tambem sei que ele'),
    ('really loves coming here.', 'adora vir aqui.'),
    ('It would actually be', 'Na verdade seria'),
    ('kind of sad if we stopped', 'meio triste se parassemos'),
    ('coming here altogether.', 'de vir aqui de vez.'),
    ("I'm just happy so long", 'Eu so fico feliz enquanto'),
    ("as he's with me~ Hoho~", 'ele estiver comigo~ Hoho~'),
    # Old Man#ve3
    ("Why don't you take", 'Por que voce nao da'),
    ('a look at my goods?', 'uma olhada nas minhas mercadorias?'),
    ("I've got many things", 'Tenho muitas coisas'),
    ('that might interest you~', 'que podem te interessar~'),
    ('Praise be to Freya,', 'Louvada seja Freya,'),
    ('who watches over us,', 'que cuida de nos,'),
    ('and blesses us with', 'e nos abencoa com'),
    ("food and drink. Don't", 'comida e bebida. Voce nao'),
    ("you think that's great,", 'acha isso otimo,'),
    ('young aventureiro?', 'jovem aventureiro?'),
    # Old Lady#ve2
    ('Owning a lot of stuff', 'Ter muitas coisas'),
    ("might seem great, but", 'pode parecer otimo, mas'),
    ("many things aren't that", 'muitas coisas nao sao tao'),
    ('valuable when you think', 'valiosas quando voce pensa'),
    ('of them in terms of', 'nelas em termos de'),
    ('real emotional value.', 'valor emocional real.'),
    ('Well, that might have been', 'Bom, isso pode ter sido'),
    ('a perigoso remark when', 'um comentario perigoso quando'),
    ("I'm trying to sell things to", 'estou tentando vender coisas para'),
    ('customers. Still, I wish', 'clientes. Ainda assim, queria'),
    ('I could carry a wider', 'poder ter uma selecao'),
    ('selection of goods.', 'maior de mercadorias.'),
    ("Claro, we're here", 'Claro, estamos aqui'),
    ("in the middle of the desert,", 'no meio do deserto,'),
    ("so maybe I'm asking too much.", 'entao talvez eu esteja pedindo demais.'),
    # Kid#ve4
    ('Hey! Do you think', 'Ei! Voce acha'),
    ('I can reach the bridge', 'que eu consigo alcancar a ponte'),
    ('over there if I jump', 'ali se eu pular'),
    ('from over here? Do', 'daqui? Voce'),
    ('you think you can try it?', 'acha que consegue tentar?'),
    ("What?! You can't do it?", 'O que?! Voce nao consegue?'),
    ("Well, I'm gonna be different", 'Bom, eu vou ser diferente'),
    ("when I grow up! I'm gonna", 'quando crescer! Eu vou'),
    ("be the world's best jumper!", 'ser o melhor saltador do mundo!'),
    ("I'm gonna be able to jump", 'Vou conseguir pular'),
    ('all the way to the mooooon!', 'ate a luuuuua!'),
    # Towner#ve13
    ('The clothes we make here', 'As roupas que fazemos aqui'),
    ('are high, airy, and sewn', 'sao leves, arejadas e costuradas'),
    ('with high quality fabric.', 'com tecido de alta qualidade.'),
    ('Claro, we need to wear', 'Claro, precisamos usar'),
    ('stuff like this since the', 'coisas assim ja que o'),
    ('weather is unbearably hot.', 'clima e insuportavelmente quente.'),
    ("The fabric? Well,", 'O tecido? Bom,'),
    ("I'll give you a hint.", 'vou te dar uma dica.'),
    ("It's made of something", 'E feito de algo'),
    ('related to camels. Heh!', 'relacionado a camelos. Heh!'),
    ("I'll leave you to figure it", 'Vou deixar voce descobrir'),
    ('out on your own. Haha!', 'por conta propria. Haha!'),
    # Continue with remaining NPCs...
    ('Let me tell you a secret.', 'Deixa eu te contar um segredo.'),
    ('But promise not to tell', 'Mas prometa nao contar'),
    ('anyone else about it, okay?', 'pra mais ninguem, ta?'),
    ('When the time comes,', 'Quando chegar a hora,'),
    ('the Temple of Cheshrumnir', 'o Templo de Cheshrumnir'),
    ('will open up and the giant', 'vai se abrir e o gigante'),
    ('Freya robot will launch!', 'robo de Freya vai ser lancado!'),
    ("It'll destroy every country", 'Ele vai destruir todos os paises'),
    ('except Arunafeltz!', 'exceto Arunafeltz!'),
    ('That robot can blow', 'Esse robo pode soprar'),
    ('hurricanes from its mouth,', 'furacoes pela boca,'),
    ('and shoot lightning from', 'e disparar relampagos dos'),
    ('its horns, and it can fire', 'seus chifres, e pode lancar'),
    ('its fists away, and its', 'seus punhos, e seu'),
    ('chest is a flame thrower!', 'peito e um lanca-chamas!'),
    ('..............................', '..............................'),
    ("You don't believe me, either.", 'Voce tambem nao acredita em mim.'),
    ("What did you just say? Zinger?", 'O que voce disse? Zinger?'),
    ("Amazing Z? The hell's that?", 'Amazing Z? Que diabos e isso?'),
    # Kid#ve5
    ("Argh! I'm a war god", 'Argh! Eu sou um deus da guerra'),
    ('protecting Goddess Freya', 'protegendo a Deusa Freya'),
    ('and Arunafeltz! Ahhhhh!', 'e Arunafeltz! Ahhhhh!'),
    ('Death to all our enemies!', 'Morte a todos os nossos inimigos!'),
    ('Burn, heretics, buuurn!', 'Queimem, hereges, queeeimem!'),
    ('Destroy your homes, your', 'Destruam seus lares, suas'),
    ('families, and build a new', 'familias, e construam um novo'),
    ('perfect world for Freya!', 'mundo perfeito para Freya!'),
    ("Hee hee! Doesn't that", 'Hee hee! Isso nao'),
    ('sound wonderful! When', 'parece maravilhoso! Quando'),
    ('I grow up, I wanna be', 'eu crescer, quero ser'),
    ('that kind of hero!', 'esse tipo de heroi!'),
    # Old Man#ve4
    ('Fr... Fr...', 'Fr... Fr...'),
    ('Fr...', 'Fr...'),
    ('Praise Freya! ^333333*Keck*^000000', 'Louvada Freya! ^333333*Tossida*^000000'),
    ('^333333*Cough cough*^000000 Fre...', '^333333*Tosse tosse*^000000 Fre...'),
    ('^333333*Cough*^000000 Praise Freya!', '^333333*Tosse*^000000 Louvada Freya!'),
    ('Freya! Conquer those', 'Freya! Conquiste aqueles'),
    ('that blaspheme you! Let', 'que te blasfemam! Deixe-me'),
    ('me see it before I die!', 'ver isso antes de morrer!'),
    ('I have never regretted', 'Eu nunca me arrependi'),
    ('^333333*Cough*^000000 my faith in you,', '^333333*Tosse*^000000 da minha fe em voce,'),
    ('my goddess! ^333333*Keck*^000000 May', 'minha deusa! ^333333*Tossida*^000000 Que'),
    ('the suffering of all our', 'o sofrimento de todos os nossos'),
    ('enemies drive them to', 'inimigos os leve a'),
    ('madness before death!', 'loucura antes da morte!'),
    # Old Lady#ve3
    ('I wonder what my', 'Me pergunto qual e minha'),
    ('standing with Freya', 'posicao com Freya.'),
    ('is like. Hopefully, she', 'Espero que ela'),
    ('will take mercy upon me', 'tenha piedade de mim'),
    ('when I leave this world.', 'quando eu deixar este mundo.'),
    ('My days here are numbered...', 'Meus dias aqui estao contados...'),
    # Kid#ve6
    ("Huh? You don't live here.", 'Huh? Voce nao mora aqui.'),
    ('Are you... Are you a traveler?', 'Voce e... Voce e um viajante?'),
    ('You musta been to so many', 'Voce deve ter ido a tantos'),
    ('other places, huh? What', 'outros lugares, ne? Como'),
    ('do they look like? I want to', 'eles sao? Eu quero'),
    ('travel too when I grow up~', 'viajar tambem quando crescer~'),
    ('I like this town, but I want', 'Eu gosto desta cidade, mas quero'),
    ('to see how other people live.', 'ver como outras pessoas vivem.'),
    ('The grown-ups think it', "Os adultos acham que e uma"),
    ("s a bad", "ma"),
    ("idea, though. They say Freya", 'ideia, no entanto. Eles dizem que Freya'),
    ('hates it. Is it that bad that', 'odeia isso. E tao ruim assim que'),
    ("I can't stop wondering?", 'eu nao consigo parar de imaginar?'),
    # Old Man#ve5
    ('Oh. You must be', 'Ah. Voce deve estar'),
    ('sightseeing. Um,', 'passeando. Hmm,'),
    ('Veins is a small town,', 'Veins e uma cidade pequena,'),
    ('visit Cheshrumnir Temple?', 'visite o Templo de Cheshrumnir?'),
    ('I hope you enjoy', 'Espero que aproveite'),
    ("your stay. Now if", 'sua estadia. Agora se'),
    ("you'll excuse me, I'd", 'me da licenca, eu gostaria'),
    ('like to continue with', 'de continuar com'),
    ('my prayers to Freya.', 'minhas oracoes a Freya.'),
    ('Oh, gracious Freya, your', 'Oh, graciosa Freya, seu'),
    ('servant humbly beseeches', 'servo humildemente suplica'),
    ('you on bended knee...', 'a voce de joelhos...'),
    ('Heal me of this infirmity!', 'Cure-me desta enfermidade!'),
    ('The body is droopingly limp,', 'O corpo esta caindo de fraqueza,'),
    ('but the spirit is willing...!', 'mas o espirito esta disposto...!'),
    ('must be... Cheshrumnir Temple.', 'deve ser... Templo de Cheshrumnir.'),
    # Towner#ve15
    ("You know what's good", 'Sabe o que e bom'),
    ('about the desert? No?', 'no deserto? Nao?'),
    ('The desert makes you', 'O deserto te torna'),
    ("stronger. Understand", 'mais forte. Entende'),
    ("what I mean? Heh, you'll", 'o que eu quero dizer? Heh, voce vai'),
    ('know as you spend more', 'saber conforme passar mais'),
    ('time here in the desert.', 'tempo aqui no deserto.'),
    # Inside Veins
    ('Unbelievable!', 'Inacreditavel!'),
    ('What kind of country', 'Que tipo de pais'),
    ('is this?! How can you', 'e esse?! Como podem'),
    ('lock me up just because', 'me prender so porque'),
    ("I don't believe in Freya?!", 'eu nao acredito em Freya?!'),
    ("This isn't civilized!", 'Isso nao e civilizado!'),
    ("You're a bunch of savages", 'Voces sao um bando de selvagens'),
    ("if you can't respect my", 'se nao conseguem respeitar minhas'),
    ('beliefs, you know that?', 'crencas, sabiam disso?'),
    ('Someone, someone help!', 'Alguem, alguem me ajude!'),
    ('This place ensures that', 'Este lugar garante que'),
    ('perigoso criminals aren', 'criminosos perigosos nao'),
    ("t threatening the publi--", 'ameacem o publi--'),
    ('Wait. Why are you even', 'Espere. Por que voce esta'),
    ("here?! This place isn't", 'aqui?! Este lugar nao e'),
    ('safe for you! Leave!', 'seguro pra voce! Saia!'),
    ("I'm grateful that our", 'Sou grato que nossa'),
    ('town is relatively peaceful.', 'cidade e relativamente pacifica.'),
    ('If it were any other place,', 'Se fosse qualquer outro lugar,'),
    ('that tiny cell would be', 'aquela cela minuscula estaria'),
    ('crammed full of criminals.', 'abarrotada de criminosos.'),
    ('Thank Freya that I', "Gracas a Freya que eu"),
    ("ve", ''),
    ('been assigned to such', 'fui designado para um'),
    ('a peaceful, quiet place.', 'lugar tao pacifico e tranquilo.'),
    ('^333333*Pant Pant*^000000', '^333333*Ofegante*^000000'),
    ('I must study as hard as I can', 'Devo estudar o maximo que puder'),
    ('for the grace of Goddess Freya.', 'pela graca da Deusa Freya.'),
    ('I really believe that', 'Eu realmente acredito que'),
    ('I can serve Freya one of', 'posso servir Freya um'),
    ('hoje em dia if I can just', 'dia desses se eu apenas'),
    ('expand my knowledge.', 'expandir meu conhecimento.'),
    ("It's too hot...", 'Esta quente demais...'),
    ('So sweaty...', 'Tao suado...'),
    ('Tricked you!', 'Te enganei!'),
    ('Thought I was dead,', 'Achou que eu estava morto,'),
    ("didn't you? Hahaha~", 'ne? Hahaha~'),
    ('The drinks in this', 'As bebidas desta'),
    ("town are so... They're...", 'cidade sao tao... Sao...'),
    ("They're so damn strong!", 'Sao absurdamente fortes!'),
    ('Why does the ground', 'Por que o chao'),
    ("keep wobbling?! It's...", 'fica balancando?! E...'),
    ("It's like it's trying to", 'Parece que esta tentando'),
    ('betray me! Every time!', 'me trair! Toda vez!'),
    ('^333333*Hiccup*^000000', '^333333*Soluco*^000000'),
    ("It's nice when a town", 'E legal quando uma cidade'),
    ("is peaceful and quiet...", 'e pacifica e tranquila...'),
    ("But it's lame when a", 'Mas e chato quando uma'),
    ('tavern is dead like this.', 'taverna esta morta assim.'),
    ("Well, there's good", 'Bom, tem pontos'),
    ('and bad points to', 'bons e ruins em'),
    ('everything. Hopefully', 'tudo. Espero que'),
    ('things will pick up', 'as coisas melhorem'),
    ('around here as more of', 'por aqui conforme mais'),
    ('you aventureiros come visit.', 'voces aventureiros venham visitar.'),
    ("There's nothing but", 'Nao tem nada alem de'),
    ('old people and children', 'velhos e criancas'),
    ("in this town. Where's a", "nesta cidade. Onde esta um"),
    ('decent man worth marrying?', 'homem decente que vale a pena casar?'),
    ("There's a few bachelors that", 'Tem uns solteiros que'),
    ('are my age, but... Well...', 'tem minha idade, mas... Bom...'),
    ("They're all too hairy or", 'Sao todos peludos demais ou'),
    ("too muscular. I don't think", 'musculosos demais. Nao acho'),
    ("I'll be able to get married", 'que vou conseguir casar'),
    ('anytime soon! Oh, the misery!', 'tao cedo! Ah, que miseria!'),
    ("Well, our town doesn't", 'Bom, nossa cidade nao'),
    ('have a choice but to', 'tem escolha senao'),
    ('defend itself in perigoso', 'se defender em tempos'),
    ('times. The young men we', 'perigosos. Os rapazes que'),
    ('have here are all buff and', 'temos aqui sao todos fortes e'),
    ('tough to protect us.', 'duroes pra nos proteger.'),
    ('They may not be bonito,', 'Eles podem nao ser bonitos,'),
    ('but they have kind and', 'mas tem coracoes gentis e'),
    ("gentle hearts. It's a pity", 'bondosos. E uma pena'),
    ('that the women here', 'que as mulheres aqui'),
    ('are more concerned', 'estao mais preocupadas'),
    ('with appearances.', 'com aparencias.'),
    ("Don't judge a book", 'Nao julgue um livro'),
    ('by its cover, but', 'pela capa, mas'),
    ('by its contents.', 'pelo seu conteudo.'),
    ('This storage solely', 'Este deposito existe'),
    ('exists for serious drinkers.', 'exclusivamente para bebedores serios.'),
    ("If it's ever shut down,", 'Se algum dia for fechado,'),
    ('I think everyone in town', 'acho que todo mundo na cidade'),
    ('will riot. Crazy, huh?', 'vai se revoltar. Loucura, ne?'),
    ('Veins is famous for its', 'Veins e famosa pela sua'),
    ('wide variety of delicious,', 'grande variedade de deliciosas'),
    ("irresistible liquor. Just one", 'e irresistiveis bebidas. So um'),
    ("sip's enough to hook you.", 'gole e o suficiente pra te fisgar.'),
    ('Praise Freya for', 'Louvada Freya por'),
    ('blessing us with the', 'nos abencoar com o'),
    ('gift of awesome liquor.', 'dom de bebida incrivel.'),
    ('Her graciousness, her', 'Sua generosidade, sua'),
    ('compassion, her liquor', 'compaixao, sua bebida'),
    ('is limitless. Let us pray.', 'e ilimitada. Vamos rezar.'),
    ('I really want to', 'Eu realmente quero'),
    ('ask out the woman', 'convidar a mulher'),
    ('right in front of me.', 'bem na minha frente pra sair.'),
    ("Do you think she'll...?", 'Voce acha que ela vai...?'),
    ('Crap! Did I say that', 'Droga! Eu disse isso'),
    ('out loud? I-I-I really', 'em voz alta? E-e-eu realmente'),
    ("didn't want her to hear!", 'nao queria que ela ouvisse!'),
    ('I heard all that...', 'Eu ouvi tudo...'),
    ("Gosh, he's so clueless.", 'Puxa, ele e tao desligado.'),
    ("I don't hate him, but he", 'Nao o odeio, mas ele'),
    ('should show a bit more', 'deveria mostrar um pouco mais'),
    ('backbone if he wants', 'de coragem se quiser'),
    ('to impress me. Hmmm...', 'me impressionar. Hmmm...'),
    ('If you enjoy a good,', 'Se voce gosta de uma boa'),
    ('stiff drink, then you have', 'bebida forte, entao voce precisa'),
    ('to stop by Veins Taberna~', 'parar na Taverna de Veins~'),
    ("If you don't love", 'Se voce nao ama'),
    ('drinking, then Veins', 'beber, entao a'),
    ('Taberna is the perfect', 'Taverna de Veins e o lugar'),
    ('place to learn! ...To', 'perfeito pra aprender! ...A'),
    ('love... drinking...', 'amar... beber...'),
    ("Isn't the sun so hot?", 'O sol nao esta muito quente?'),
    ("Doesn't it make you feel", 'Isso nao te faz sentir'),
    ('so thirsty? Well, you may', 'muita sede? Bom, voce pode'),
    ('want to consider quenching', 'querer considerar matar'),
    ('that nasty thirst with liquor!', 'essa sede maldita com bebida!'),
    ('My job is to serve', 'Meu trabalho e servir'),
    ('delicious, life giving', 'bebida deliciosa e revigorante'),
    ('liquor to my customers to', 'para meus clientes para'),
    ('relieve their parched throats.', 'aliviar suas gargantas secas.'),
    ('Seeing their drunken smiles', 'Ver seus sorrisos bebados'),
    ('really makes my day~', 'realmente alegra meu dia~'),
    ('A lone wolf of the desert.', 'Um lobo solitario do deserto.'),
    ("That's me. Well, that's why", 'Esse sou eu. Bom, e por isso que'),
    ("I'm drinking here alone.", 'estou bebendo aqui sozinho.'),
    ('Sweet Freya, these', 'Doce Freya, essas'),
    ('drinks are so good.', 'bebidas sao tao boas.'),
    ('I could drink all day.', 'Eu poderia beber o dia todo.'),
    ("Man, the world is just...", 'Cara, o mundo e apenas...'),
    ("It's just desires...!", 'Sao apenas desejos...!'),
    ('Faith? It helps, you', 'Fe? Ajuda, sabe?'),
    ('know? Cuz-cuz desires', 'Porque-porque desejos'),
    ('are all just nothing!', 'sao todos nada!'),
    ("They're nooooooothing!", 'Sao naaaaaada!'),
    ("Argh! What is life?!", 'Argh! O que e a vida?!'),
    ("I don't know what to", 'Nao sei em que'),
    ('believe anymore! Freya!', 'acreditar mais! Freya!'),
    ('Freya looooves you!', 'Freya te aaaaama!'),
]

with open('npc/cities/veins.txt', 'r', encoding='utf-8') as f:
    content = f.read()

for old, new in veins_content_replacements:
    content = content.replace(old, new)

with open('npc/cities/veins.txt', 'w', encoding='utf-8') as f:
    f.write(content)

print("Veins fully translated")
