#!/usr/bin/env python3
"""
Translate rAthena NPC quest files from English to Brazilian Portuguese.
Only translates text inside mes "..." and select("...") / select("...", "...")
Does NOT change: variable names, function calls, NPC names in brackets,
item names, map names, coordinates, script logic, comments.
Uses informal Brazilian Portuguese WITHOUT accented characters.
"""

import re
import os
import glob

# Common phrase translations (order matters - longer/more specific first)
PHRASE_MAP = {
    # Common menu options
    "Cancel.": "Cancelar.",
    "Cancel": "Cancelar",
    "End Dialog": "Encerrar Dialogo",
    "Quit": "Sair",
    "YES": "SIM",
    "NO": "NAO",
    "Yes": "Sim",
    "No": "Nao",
    "Yes.": "Sim.",
    "No.": "Nao.",
    "Accept": "Aceitar",
    "Refuse": "Recusar",
    "Accept the mission.": "Aceitar a missao.",
    "Check the Missions.": "Ver as Missoes.",
    "Next": "Proximo",
    "Previous": "Anterior",
    "Continue": "Continuar",
    "Continue.": "Continuar.",
    "Back": "Voltar",
    "Leave": "Sair",
    "Leave.": "Sair.",
    "Stay": "Ficar",
    "Buy": "Comprar",
    "Sell": "Vender",
    "OK": "OK",
    "I want to learn": "Eu quero aprender",

    # Very common full mes lines
    "You have completed the mission.": "Voce completou a missao.",
    "Here is your reward.": "Aqui esta sua recompensa.",
    "You have accepted the mission.": "Voce aceitou a missao.",
    "There is nothing special to do.": "Nao ha nada especial para fazer.",
    "You may now view the bulletin board.": "Voce pode ver o quadro de avisos agora.",
    "Mission bulletin board.": "Quadro de missoes.",
    "You are not an Eden group member. You are not qualified to access the bulletin board.": "Voce nao e membro do grupo Eden. Voce nao esta qualificado para acessar o quadro de avisos.",

    # Common hunting mission patterns
    " Hunting": " Cacada",

    # Common words/phrases for contextual translation
}

def translate_text(text):
    """Translate English text to Brazilian Portuguese without accented chars."""
    if not text or not text.strip():
        return text

    # Skip if already translated
    if any(pt_word in text for pt_word in ["voce", "Voce", "Cancelar", "missao", "Missao", "nao e", "Nao e"]):
        return text

    # Skip NPC name lines like "[Name]" - these are just NPC identifiers
    stripped = text.strip()
    if stripped.startswith("[") and stripped.endswith("]"):
        return text

    # Skip lines that are purely color codes, formatting, or very short symbols
    if stripped in ["...", "..", ".", "+", "-", "~", "!", "?", "*"]:
        return text

    # Skip lines with just special characters or numbers
    if re.match(r'^[\d\s\.\-\+\*\~\!\?\#\=]+$', stripped):
        return text

    # Apply direct phrase mappings
    for eng, ptbr in PHRASE_MAP.items():
        if text == eng:
            return ptbr

    # Full line translations using the comprehensive translator
    result = translate_line(text)
    return result


def translate_line(text):
    """Translate a single line of dialogue text."""
    # This is the main translation engine
    # We'll use pattern-based translation

    t = text

    # Preserve color codes and special formatting
    # Extract them, translate, put them back

    # Common full sentences and patterns
    replacements = [
        # Greetings and common phrases
        ("Hello", "Ola"),
        ("hello", "ola"),
        ("Hi there", "Oi"),
        ("hi there", "oi"),
        ("Good morning", "Bom dia"),
        ("Good afternoon", "Boa tarde"),
        ("Good evening", "Boa noite"),
        ("Good luck", "Boa sorte"),
        ("good luck", "boa sorte"),
        ("Thank you", "Obrigado"),
        ("Thanks", "Obrigado"),
        ("thanks", "obrigado"),
        ("thank you", "obrigado"),
        ("Welcome", "Bem-vindo"),
        ("welcome", "bem-vindo"),
        ("Goodbye", "Adeus"),
        ("goodbye", "adeus"),
        ("Good bye", "Adeus"),
        ("Farewell", "Ate mais"),
        ("farewell", "ate mais"),
        ("Please", "Por favor"),
        ("please", "por favor"),
        ("Sorry", "Desculpe"),
        ("sorry", "desculpe"),
        ("Excuse me", "Com licenca"),
        ("excuse me", "com licenca"),

        # Pronouns and common words
        ("I am ", "Eu sou "),
        ("I'm ", "Eu sou "),
        ("i'm ", "eu sou "),
        ("I have ", "Eu tenho "),
        ("I've ", "Eu tenho "),
        ("I don't ", "Eu nao "),
        ("I can't ", "Eu nao consigo "),
        ("I can ", "Eu consigo "),
        ("I will ", "Eu vou "),
        ("I'll ", "Eu vou "),
        ("I would ", "Eu gostaria de "),
        ("I'd ", "Eu gostaria de "),
        ("I want ", "Eu quero "),
        ("I need ", "Eu preciso de "),
        ("I know ", "Eu sei "),
        ("I think ", "Eu acho "),
        ("I heard ", "Eu ouvi "),
        ("I got ", "Eu tenho "),
        ("I was ", "Eu estava "),
        ("I had ", "Eu tinha "),
        ("You are ", "Voce e "),
        ("You're ", "Voce e "),
        ("you're ", "voce e "),
        ("You have ", "Voce tem "),
        ("You've ", "Voce tem "),
        ("you've ", "voce tem "),
        ("You don't ", "Voce nao "),
        ("you don't ", "voce nao "),
        ("You can't ", "Voce nao pode "),
        ("you can't ", "voce nao pode "),
        ("You can ", "Voce pode "),
        ("you can ", "voce pode "),
        ("You will ", "Voce vai "),
        ("You'll ", "Voce vai "),
        ("you'll ", "voce vai "),
        ("You would ", "Voce deveria "),
        ("You'd ", "Voce deveria "),
        ("You want ", "Voce quer "),
        ("you want ", "voce quer "),
        ("You need ", "Voce precisa "),
        ("you need ", "voce precisa "),
        ("You should ", "Voce deveria "),
        ("you should ", "voce deveria "),
        ("You must ", "Voce deve "),
        ("you must ", "voce deve "),
        ("You may ", "Voce pode "),
        ("you may ", "voce pode "),
        ("You might ", "Voce pode "),
        ("you might ", "voce pode "),
        ("You seem ", "Voce parece "),
        ("you seem ", "voce parece "),
        ("You look ", "Voce parece "),
        ("you look ", "voce parece "),
        ("you know", "voce sabe"),
        ("You know", "Voce sabe"),

        ("We are ", "Nos estamos "),
        ("We're ", "Nos estamos "),
        ("we're ", "nos estamos "),
        ("We have ", "Nos temos "),
        ("We've ", "Nos temos "),
        ("we've ", "nos temos "),
        ("We don't ", "Nos nao "),
        ("We can ", "Nos podemos "),
        ("we can ", "nos podemos "),
        ("We need ", "Nos precisamos "),
        ("we need ", "nos precisamos "),
        ("We will ", "Nos vamos "),
        ("We'll ", "Nos vamos "),

        ("They are ", "Eles sao "),
        ("They're ", "Eles sao "),
        ("they're ", "eles sao "),
        ("They have ", "Eles tem "),
        ("They've ", "Eles tem "),
        ("They don't ", "Eles nao "),
        ("They can ", "Eles podem "),
        ("They will ", "Eles vao "),
        ("They'll ", "Eles vao "),

        ("He is ", "Ele e "),
        ("He's ", "Ele e "),
        ("She is ", "Ela e "),
        ("She's ", "Ela e "),
        ("It is ", "Isso e "),
        ("It's ", "E "),
        ("it's ", "e "),
        ("It was ", "Era "),
        ("it was ", "era "),

        ("There is ", "Ha "),
        ("There are ", "Ha "),
        ("there is ", "ha "),
        ("there are ", "ha "),
        ("There's ", "Ha "),
        ("there's ", "ha "),

        # Questions
        ("What is ", "O que e "),
        ("What's ", "O que e "),
        ("what is ", "o que e "),
        ("what's ", "o que e "),
        ("What are ", "O que sao "),
        ("what are ", "o que sao "),
        ("What do ", "O que "),
        ("what do ", "o que "),
        ("What did ", "O que "),
        ("what did ", "o que "),
        ("What happened", "O que aconteceu"),
        ("what happened", "o que aconteceu"),
        ("Where is ", "Onde esta "),
        ("Where's ", "Onde esta "),
        ("where is ", "onde esta "),
        ("Where are ", "Onde estao "),
        ("where are ", "onde estao "),
        ("Where do ", "Onde "),
        ("where do ", "onde "),
        ("When did ", "Quando "),
        ("when did ", "quando "),
        ("When do ", "Quando "),
        ("when do ", "quando "),
        ("How do ", "Como "),
        ("how do ", "como "),
        ("How is ", "Como esta "),
        ("how is ", "como esta "),
        ("How are ", "Como estao "),
        ("how are ", "como estao "),
        ("How can ", "Como pode "),
        ("how can ", "como pode "),
        ("How about ", "Que tal "),
        ("how about ", "que tal "),
        ("How much ", "Quanto "),
        ("how much ", "quanto "),
        ("How many ", "Quantos "),
        ("how many ", "quantos "),
        ("Why do ", "Por que "),
        ("why do ", "por que "),
        ("Why is ", "Por que "),
        ("why is ", "por que "),
        ("Why are ", "Por que "),
        ("why are ", "por que "),
        ("Who is ", "Quem e "),
        ("Who's ", "Quem e "),
        ("who is ", "quem e "),
        ("Who are ", "Quem sao "),
        ("who are ", "quem sao "),
        ("Can you ", "Voce pode "),
        ("can you ", "voce pode "),
        ("Could you ", "Voce poderia "),
        ("could you ", "voce poderia "),
        ("Would you ", "Voce gostaria de "),
        ("would you ", "voce gostaria de "),
        ("Do you ", "Voce "),
        ("do you ", "voce "),
        ("Did you ", "Voce "),
        ("did you ", "voce "),
        ("Don't you ", "Voce nao "),
        ("don't you", "voce nao"),
        ("Have you ", "Voce ja "),
        ("have you ", "voce ja "),
        ("Are you ", "Voce e "),
        ("are you ", "voce e "),
        ("Aren't you", "Voce nao e"),
        ("aren't you", "voce nao e"),
        ("Is that ", "Isso e "),
        ("is that ", "isso e "),
        ("Is this ", "Isso e "),
        ("is this ", "isso e "),

        # Negatives
        ("don't", "nao"),
        ("Don't", "Nao"),
        ("doesn't", "nao"),
        ("Doesn't", "Nao"),
        ("didn't", "nao"),
        ("Didn't", "Nao"),
        ("can't", "nao pode"),
        ("Can't", "Nao pode"),
        ("cannot", "nao pode"),
        ("Cannot", "Nao pode"),
        ("couldn't", "nao conseguiu"),
        ("Couldn't", "Nao conseguiu"),
        ("won't", "nao vai"),
        ("Won't", "Nao vai"),
        ("wouldn't", "nao iria"),
        ("Wouldn't", "Nao iria"),
        ("shouldn't", "nao deveria"),
        ("Shouldn't", "Nao deveria"),
        ("isn't", "nao e"),
        ("Isn't", "Nao e"),
        ("aren't", "nao sao"),
        ("Aren't", "Nao sao"),
        ("wasn't", "nao era"),
        ("Wasn't", "Nao era"),
        ("weren't", "nao eram"),
        ("Weren't", "Nao eram"),
        ("haven't", "nao tenho"),
        ("Haven't", "Nao tenho"),
        ("hasn't", "nao tem"),
        ("Hasn't", "Nao tem"),
        ("hadn't", "nao tinha"),
        ("mustn't", "nao deve"),
        ("needn't", "nao precisa"),

        # Contractions
        ("Let's", "Vamos"),
        ("let's", "vamos"),
        ("Let me", "Deixe-me"),
        ("let me", "deixe-me"),

        # Common verbs and phrases
        ("Come back", "Volte"),
        ("come back", "volte"),
        ("Go ahead", "Va em frente"),
        ("go ahead", "va em frente"),
        ("Go away", "Va embora"),
        ("go away", "va embora"),
        ("Get out", "Saia"),
        ("get out", "saia"),
        ("Come in", "Entre"),
        ("come in", "entre"),
        ("Give me", "Me de"),
        ("give me", "me de"),
        ("Tell me", "Me diga"),
        ("tell me", "me diga"),
        ("Show me", "Me mostre"),
        ("show me", "me mostre"),
        ("Help me", "Me ajude"),
        ("help me", "me ajude"),
        ("Wait a moment", "Espere um momento"),
        ("wait a moment", "espere um momento"),
        ("Wait a sec", "Espere um pouco"),
        ("Wait a minute", "Espere um minuto"),
        ("Be careful", "Tenha cuidado"),
        ("be careful", "tenha cuidado"),
        ("Be prepared", "Esteja preparado"),
        ("be prepared", "esteja preparado"),
        ("Take care", "Se cuide"),
        ("take care", "se cuide"),
        ("Come again", "Volte novamente"),
        ("come again", "volte novamente"),
        ("of course", "e claro"),
        ("Of course", "E claro"),

        # RPG/Game specific
        ("adventurer", "aventureiro"),
        ("Adventurer", "Aventureiro"),
        ("adventurers", "aventureiros"),
        ("Adventurers", "Aventureiros"),
        ("warrior", "guerreiro"),
        ("Warrior", "Guerreiro"),
        ("warriors", "guerreiros"),
        ("Warriors", "Guerreiros"),
        ("monster", "monstro"),
        ("Monster", "Monstro"),
        ("monsters", "monstros"),
        ("Monsters", "Monstros"),
        ("quest", "missao"),
        ("Quest", "Missao"),
        ("quests", "missoes"),
        ("Quests", "Missoes"),
        ("mission", "missao"),
        ("Mission", "Missao"),
        ("missions", "missoes"),
        ("Missions", "Missoes"),
        ("reward", "recompensa"),
        ("Reward", "Recompensa"),
        ("rewards", "recompensas"),
        ("Rewards", "Recompensas"),
        ("dangerous", "perigoso"),
        ("Dangerous", "Perigoso"),
        ("danger", "perigo"),
        ("Danger", "Perigo"),
        ("experience", "experiencia"),
        ("Experience", "Experiencia"),
        ("level", "nivel"),
        ("Level", "Nivel"),
        ("weapon", "arma"),
        ("Weapon", "Arma"),
        ("weapons", "armas"),
        ("Weapons", "Armas"),
        ("armor", "armadura"),
        ("Armor", "Armadura"),
        ("shield", "escudo"),
        ("Shield", "Escudo"),
        ("sword", "espada"),
        ("Sword", "Espada"),
        ("magic", "magia"),
        ("Magic", "Magia"),
        ("spell", "feitico"),
        ("Spell", "Feitico"),
        ("spells", "feiticos"),
        ("power", "poder"),
        ("Power", "Poder"),
        ("powerful", "poderoso"),
        ("Powerful", "Poderoso"),
        ("strength", "forca"),
        ("Strength", "Forca"),
        ("strong", "forte"),
        ("Strong", "Forte"),
        ("weak", "fraco"),
        ("Weak", "Fraco"),
        ("enemy", "inimigo"),
        ("Enemy", "Inimigo"),
        ("enemies", "inimigos"),
        ("Enemies", "Inimigos"),
        ("battle", "batalha"),
        ("Battle", "Batalha"),
        ("fight", "lutar"),
        ("Fight", "Lutar"),
        ("attack", "atacar"),
        ("Attack", "Atacar"),
        ("attacks", "ataques"),
        ("attacking", "atacando"),
        ("defend", "defender"),
        ("Defend", "Defender"),
        ("protect", "proteger"),
        ("Protect", "Proteger"),
        ("destroy", "destruir"),
        ("Destroy", "Destruir"),
        ("kill", "matar"),
        ("Kill", "Matar"),
        ("hunt", "cacar"),
        ("Hunt", "Cacar"),
        ("hunting", "cacando"),
        ("Hunting", "Cacada"),
        ("treasure", "tesouro"),
        ("Treasure", "Tesouro"),
        ("gold", "ouro"),
        ("Gold", "Ouro"),
        ("money", "dinheiro"),
        ("Money", "Dinheiro"),
        ("village", "vila"),
        ("Village", "Vila"),
        ("town", "cidade"),
        ("Town", "Cidade"),
        ("city", "cidade"),
        ("City", "Cidade"),
        ("kingdom", "reino"),
        ("Kingdom", "Reino"),
        ("castle", "castelo"),
        ("Castle", "Castelo"),
        ("dungeon", "masmorra"),
        ("Dungeon", "Masmorra"),
        ("dungeons", "masmorras"),
        ("Dungeons", "Masmorras"),
        ("forest", "floresta"),
        ("Forest", "Floresta"),
        ("mountain", "montanha"),
        ("Mountain", "Montanha"),
        ("cave", "caverna"),
        ("Cave", "Caverna"),
        ("island", "ilha"),
        ("Island", "Ilha"),
        ("temple", "templo"),
        ("Temple", "Templo"),
        ("tower", "torre"),
        ("Tower", "Torre"),
        ("guild", "guilda"),
        ("Guild", "Guilda"),
        ("group", "grupo"),
        ("Group", "Grupo"),
        ("member", "membro"),
        ("Member", "Membro"),
        ("members", "membros"),
        ("Members", "Membros"),
        ("leader", "lider"),
        ("Leader", "Lider"),
        ("friend", "amigo"),
        ("Friend", "Amigo"),
        ("friends", "amigos"),
        ("hero", "heroi"),
        ("Hero", "Heroi"),
        ("king", "rei"),
        ("King", "Rei"),
        ("queen", "rainha"),
        ("Queen", "Rainha"),
        ("prince", "principe"),
        ("Prince", "Principe"),
        ("princess", "princesa"),
        ("Princess", "Princesa"),
        ("soldier", "soldado"),
        ("Soldier", "Soldado"),
        ("soldiers", "soldados"),
        ("guard", "guarda"),
        ("Guard", "Guarda"),
        ("guards", "guardas"),
        ("captain", "capitao"),
        ("Captain", "Capitao"),
        ("merchant", "mercador"),
        ("Merchant", "Mercador"),
        ("blacksmith", "ferreiro"),
        ("Blacksmith", "Ferreiro"),
        ("priest", "sacerdote"),
        ("Priest", "Sacerdote"),
        ("thief", "ladrao"),
        ("Thief", "Ladrao"),
        ("mage", "mago"),
        ("Mage", "Mago"),
        ("knight", "cavaleiro"),
        ("Knight", "Cavaleiro"),
        ("assassin", "assassino"),
        ("Assassin", "Assassino"),
        ("hunter", "cacador"),
        ("Hunter", "Cacador"),
        ("alchemist", "alquimista"),
        ("Alchemist", "Alquimista"),
        ("wizard", "bruxo"),
        ("Wizard", "Bruxo"),
        ("sage", "sabio"),
        ("Sage", "Sabio"),

        # Common adjectives
        ("beautiful", "bonito"),
        ("Beautiful", "Bonito"),
        ("terrible", "terrivel"),
        ("Terrible", "Terrivel"),
        ("amazing", "incrivel"),
        ("Amazing", "Incrivel"),
        ("wonderful", "maravilhoso"),
        ("Wonderful", "Maravilhoso"),
        ("great", "otimo"),
        ("Great", "Otimo"),
        ("good", "bom"),
        ("Good", "Bom"),
        ("bad", "ruim"),
        ("Bad", "Ruim"),
        ("old", "velho"),
        ("Old", "Velho"),
        ("new", "novo"),
        ("New", "Novo"),
        ("big", "grande"),
        ("Big", "Grande"),
        ("small", "pequeno"),
        ("Small", "Pequeno"),
        ("little", "pequeno"),
        ("Little", "Pequeno"),
        ("much", "muito"),
        ("many", "muitos"),
        ("some", "alguns"),
        ("Some", "Alguns"),
        ("every", "cada"),
        ("Every", "Cada"),
        ("all", "todos"),
        ("All", "Todos"),
        ("other", "outro"),
        ("Other", "Outro"),
        ("another", "outro"),
        ("Another", "Outro"),
        ("same", "mesmo"),
        ("Same", "Mesmo"),
        ("different", "diferente"),
        ("Different", "Diferente"),
        ("special", "especial"),
        ("Special", "Especial"),
        ("important", "importante"),
        ("Important", "Importante"),
        ("difficult", "dificil"),
        ("Difficult", "Dificil"),
        ("easy", "facil"),
        ("Easy", "Facil"),
        ("hard", "dificil"),
        ("Hard", "Dificil"),
        ("true", "verdade"),
        ("True", "Verdade"),
        ("false", "falso"),
        ("False", "Falso"),
        ("real", "real"),
        ("alive", "vivo"),
        ("dead", "morto"),
        ("Dead", "Morto"),
        ("safe", "seguro"),
        ("Safe", "Seguro"),
        ("scared", "assustado"),
        ("scary", "assustador"),
        ("secret", "segredo"),
        ("Secret", "Segredo"),
        ("strange", "estranho"),
        ("Strange", "Estranho"),
        ("weird", "estranho"),
        ("Weird", "Estranho"),
        ("crazy", "louco"),
        ("Crazy", "Louco"),
        ("angry", "furioso"),
        ("Angry", "Furioso"),
        ("upset", "chateado"),
        ("happy", "feliz"),
        ("Happy", "Feliz"),
        ("ready", "pronto"),
        ("Ready", "Pronto"),
        ("busy", "ocupado"),
        ("Busy", "Ocupado"),
        ("tired", "cansado"),
        ("Tired", "Cansado"),
        ("hungry", "com fome"),
        ("curious", "curioso"),
        ("Curious", "Curioso"),
        ("interested", "interessado"),
        ("careful", "cuidadoso"),
        ("Careful", "Cuidadoso"),
        ("cruel", "cruel"),

        # Common nouns
        ("time", "tempo"),
        ("Time", "Tempo"),
        ("place", "lugar"),
        ("Place", "Lugar"),
        ("world", "mundo"),
        ("World", "Mundo"),
        ("life", "vida"),
        ("Life", "Vida"),
        ("death", "morte"),
        ("Death", "Morte"),
        ("people", "pessoas"),
        ("People", "Pessoas"),
        ("person", "pessoa"),
        ("family", "familia"),
        ("Family", "Familia"),
        ("house", "casa"),
        ("House", "Casa"),
        ("door", "porta"),
        ("Door", "Porta"),
        ("road", "estrada"),
        ("Road", "Estrada"),
        ("path", "caminho"),
        ("Path", "Caminho"),
        ("way", "caminho"),
        ("water", "agua"),
        ("Water", "Agua"),
        ("fire", "fogo"),
        ("Fire", "Fogo"),
        ("earth", "terra"),
        ("Earth", "Terra"),
        ("wind", "vento"),
        ("Wind", "Vento"),
        ("light", "luz"),
        ("Light", "Luz"),
        ("dark", "escuro"),
        ("Dark", "Escuro"),
        ("darkness", "escuridao"),
        ("Darkness", "Escuridao"),
        ("night", "noite"),
        ("Night", "Noite"),
        ("day", "dia"),
        ("Day", "Dia"),
        ("morning", "manha"),
        ("story", "historia"),
        ("Story", "Historia"),
        ("problem", "problema"),
        ("Problem", "Problema"),
        ("problems", "problemas"),
        ("question", "pergunta"),
        ("answer", "resposta"),
        ("reason", "razao"),
        ("thing", "coisa"),
        ("things", "coisas"),
        ("something", "algo"),
        ("Something", "Algo"),
        ("nothing", "nada"),
        ("Nothing", "Nada"),
        ("everything", "tudo"),
        ("Everything", "Tudo"),
        ("everyone", "todos"),
        ("Everyone", "Todos"),
        ("someone", "alguem"),
        ("Someone", "Alguem"),
        ("nobody", "ninguem"),
        ("Nobody", "Ninguem"),
        ("no one", "ninguem"),
        ("No one", "Ninguem"),
        ("anywhere", "qualquer lugar"),
        ("Anywhere", "Qualquer lugar"),
        ("somewhere", "algum lugar"),
        ("Somewhere", "Algum lugar"),
        ("nowhere", "nenhum lugar"),
        ("Nowhere", "Nenhum lugar"),
        ("here", "aqui"),
        ("Here", "Aqui"),
        ("there", "la"),
        ("right now", "agora mesmo"),
        ("Right now", "Agora mesmo"),
        ("right", "certo"),
        ("Right", "Certo"),
        ("wrong", "errado"),
        ("Wrong", "Errado"),
        ("enough", "suficiente"),
        ("Enough", "Suficiente"),
        ("again", "novamente"),
        ("Again", "Novamente"),
        ("always", "sempre"),
        ("Always", "Sempre"),
        ("never", "nunca"),
        ("Never", "Nunca"),
        ("sometimes", "as vezes"),
        ("today", "hoje"),
        ("Today", "Hoje"),
        ("tomorrow", "amanha"),
        ("Tomorrow", "Amanha"),
        ("yesterday", "ontem"),
        ("already", "ja"),
        ("Already", "Ja"),
        ("still", "ainda"),
        ("Still", "Ainda"),
        ("just", "apenas"),
        ("Just", "Apenas"),
        ("only", "apenas"),
        ("Only", "Apenas"),
        ("also", "tambem"),
        ("Also", "Tambem"),
        ("too", "tambem"),
        ("really", "realmente"),
        ("Really", "Realmente"),
        ("actually", "na verdade"),
        ("Actually", "Na verdade"),
        ("maybe", "talvez"),
        ("Maybe", "Talvez"),
        ("perhaps", "talvez"),
        ("Perhaps", "Talvez"),
        ("probably", "provavelmente"),
        ("Probably", "Provavelmente"),
        ("certainly", "certamente"),
        ("Certainly", "Certamente"),
        ("definitely", "definitivamente"),
        ("obviously", "obviamente"),
        ("especially", "especialmente"),
        ("exactly", "exatamente"),
        ("Exactly", "Exatamente"),
        ("suddenly", "de repente"),
        ("quickly", "rapidamente"),
        ("slowly", "devagar"),
        ("carefully", "cuidadosamente"),
        ("Carefully", "Cuidadosamente"),
        ("finally", "finalmente"),
        ("Finally", "Finalmente"),
        ("together", "juntos"),
        ("Together", "Juntos"),
        ("alone", "sozinho"),
        ("Alone", "Sozinho"),
        ("away", "embora"),
        ("inside", "dentro"),
        ("outside", "fora"),
        ("behind", "atras"),
        ("before", "antes"),
        ("Before", "Antes"),
        ("after", "depois"),
        ("After", "Depois"),
        ("between", "entre"),
        ("around", "ao redor"),
        ("around", "ao redor"),
        ("about", "sobre"),
        ("About", "Sobre"),
        ("above", "acima"),
        ("below", "abaixo"),
        ("under", "debaixo"),
        ("over", "sobre"),
        ("through", "atraves"),
        ("across", "atraves"),
        ("along", "ao longo"),
        ("near", "perto"),
        ("far", "longe"),
        ("until", "ate"),
        ("since", "desde"),
        ("during", "durante"),
        ("without", "sem"),
        ("Without", "Sem"),
        ("with", "com"),
        ("from", "de"),
        ("into", "para dentro"),
        ("very", "muito"),
        ("Very", "Muito"),
        ("more", "mais"),
        ("More", "Mais"),
        ("less", "menos"),
        ("most", "mais"),
        ("least", "menos"),
        ("than", "que"),
        ("then", "entao"),
        ("Then", "Entao"),
        ("because", "porque"),
        ("Because", "Porque"),
        ("so ", "entao "),
        ("So ", "Entao "),
        ("but ", "mas "),
        ("But ", "Mas "),
        ("and ", "e "),
        ("And ", "E "),
        ("or ", "ou "),
        ("Or ", "Ou "),
        ("if ", "se "),
        ("If ", "Se "),
        ("not ", "nao "),
        ("Not ", "Nao "),
        ("now", "agora"),
        ("Now", "Agora"),
        ("well", "bem"),
        ("Well", "Bem"),
        ("even", "ate mesmo"),
        ("first", "primeiro"),
        ("First", "Primeiro"),
        ("last", "ultimo"),
        ("Last", "Ultimo"),
        ("next", "proximo"),

        # Common verbs
        ("remember", "lembrar"),
        ("Remember", "Lembrar"),
        ("forget", "esquecer"),
        ("Forget", "Esquecer"),
        ("forgotten", "esquecido"),
        ("understand", "entender"),
        ("Understand", "Entender"),
        ("believe", "acreditar"),
        ("Believe", "Acreditar"),
        ("follow", "seguir"),
        ("Follow", "Seguir"),
        ("bring", "trazer"),
        ("Bring", "Trazer"),
        ("brought", "trouxe"),
        ("take", "pegar"),
        ("Take", "Pegar"),
        ("make", "fazer"),
        ("Make", "Fazer"),
        ("find", "encontrar"),
        ("Find", "Encontrar"),
        ("found", "encontrou"),
        ("Found", "Encontrou"),
        ("look", "olhar"),
        ("Look", "Olhar"),
        ("looking", "procurando"),
        ("see", "ver"),
        ("See", "Ver"),
        ("seen", "visto"),
        ("watch", "observar"),
        ("Watch", "Observar"),
        ("listen", "ouvir"),
        ("Listen", "Ouvir"),
        ("hear", "ouvir"),
        ("heard", "ouviu"),
        ("speak", "falar"),
        ("Speak", "Falar"),
        ("talk", "conversar"),
        ("Talk", "Conversar"),
        ("talking", "conversando"),
        ("said", "disse"),
        ("say", "dizer"),
        ("Say", "Dizer"),
        ("told", "disse"),
        ("asked", "perguntou"),
        ("called", "chamado"),
        ("know", "saber"),
        ("Know", "Saber"),
        ("knew", "sabia"),
        ("think", "pensar"),
        ("Think", "Pensar"),
        ("thought", "pensou"),
        ("try", "tentar"),
        ("Try", "Tentar"),
        ("tried", "tentou"),
        ("trying", "tentando"),
        ("start", "comecar"),
        ("Start", "Comecar"),
        ("started", "comecou"),
        ("stop", "parar"),
        ("Stop", "Parar"),
        ("keep", "manter"),
        ("Keep", "Manter"),
        ("change", "mudar"),
        ("Change", "Mudar"),
        ("changed", "mudou"),
        ("open", "abrir"),
        ("Open", "Abrir"),
        ("close", "fechar"),
        ("Close", "Fechar"),
        ("learn", "aprender"),
        ("Learn", "Aprender"),
        ("learned", "aprendeu"),
        ("teach", "ensinar"),
        ("Teach", "Ensinar"),
        ("taught", "ensinou"),
        ("teach", "ensinar"),
        ("use", "usar"),
        ("Use", "Usar"),
        ("used", "usou"),
        ("using", "usando"),
        ("need", "precisar"),
        ("Need", "Precisar"),
        ("want", "querer"),
        ("Want", "Querer"),
        ("move", "mover"),
        ("Move", "Mover"),
        ("return", "retornar"),
        ("Return", "Retornar"),
        ("leave", "sair"),
        ("Leave", "Sair"),
        ("stay", "ficar"),
        ("Stay", "Ficar"),
        ("wait", "esperar"),
        ("Wait", "Esperar"),
        ("run", "correr"),
        ("Run", "Correr"),
        ("walk", "andar"),
        ("Walk", "Andar"),
        ("go", "ir"),
        ("Go", "Ir"),
        ("come", "vir"),
        ("Come", "Vir"),
        ("get", "pegar"),
        ("Get", "Pegar"),
        ("give", "dar"),
        ("Give", "Dar"),
        ("put", "colocar"),
        ("Put", "Colocar"),
        ("set", "definir"),
        ("pay", "pagar"),
        ("Pay", "Pagar"),
        ("payment", "pagamento"),
        ("paid", "pago"),
        ("buy", "comprar"),
        ("sell", "vender"),
        ("work", "trabalhar"),
        ("Work", "Trabalhar"),
        ("working", "funcionando"),
        ("help", "ajudar"),
        ("Help", "Ajudar"),
        ("save", "salvar"),
        ("Save", "Salvar"),
        ("complete", "completar"),
        ("Complete", "Completar"),
        ("completed", "completou"),
        ("finished", "terminou"),
        ("finish", "terminar"),
        ("Finish", "Terminar"),
        ("succeed", "conseguir"),
        ("success", "sucesso"),
        ("fail", "falhar"),
        ("failed", "falhou"),
        ("die", "morrer"),
        ("died", "morreu"),
        ("happen", "acontecer"),
        ("happened", "aconteceu"),
        ("exist", "existir"),
        ("exists", "existe"),
        ("become", "se tornar"),
        ("became", "se tornou"),
        ("seem", "parecer"),
        ("seems", "parece"),
        ("appear", "aparecer"),
        ("appears", "aparece"),
        ("disappear", "desaparecer"),
        ("mean", "significa"),
        ("means", "significa"),
        ("belong", "pertencer"),
        ("belongs", "pertence"),
        ("wonder", "imaginar"),
        ("worry", "preocupar"),
        ("worried", "preocupado"),
        ("prepare", "preparar"),
        ("prepared", "preparado"),
        ("collect", "coletar"),
        ("Collect", "Coletar"),
        ("collecting", "coletando"),
        ("gather", "reunir"),
        ("Gather", "Reunir"),
        ("deliver", "entregar"),
        ("Deliver", "Entregar"),
        ("receive", "receber"),
        ("received", "recebeu"),
        ("accept", "aceitar"),
        ("accepted", "aceitou"),
        ("refuse", "recusar"),
        ("create", "criar"),
        ("created", "criou"),
        ("build", "construir"),
        ("built", "construiu"),
        ("break", "quebrar"),
        ("broken", "quebrado"),
        ("repair", "consertar"),
        ("fix", "consertar"),
        ("check", "verificar"),
        ("Check", "Verificar"),
        ("inspect", "inspecionar"),
        ("investigate", "investigar"),
        ("Investigate", "Investigar"),
        ("explore", "explorar"),
        ("Explore", "Explorar"),
        ("discover", "descobrir"),
        ("discovered", "descobriu"),
        ("search", "procurar"),
        ("Search", "Procurar"),
        ("enter", "entrar"),
        ("Enter", "Entrar"),
        ("exit", "sair"),
        ("Exit", "Sair"),
        ("carry", "carregar"),
        ("carrying", "carregando"),
        ("steal", "roubar"),
        ("stolen", "roubado"),
        ("robbed", "roubado"),

        # Game-specific phrases
        ("items", "itens"),
        ("Items", "Itens"),
        ("item", "item"),
        ("Item", "Item"),
        ("equipment", "equipamento"),
        ("Equipment", "Equipamento"),
        ("skill", "habilidade"),
        ("Skill", "Habilidade"),
        ("skills", "habilidades"),
        ("Skills", "Habilidades"),
        ("zeny", "zeny"),
        ("Zeny", "Zeny"),
        ("ingredient", "ingrediente"),
        ("ingredients", "ingredientes"),
        ("material", "material"),
        ("materials", "materiais"),
        ("recipe", "receita"),
        ("Recipe", "Receita"),
        ("information", "informacao"),
        ("Information", "Informacao"),
        ("details", "detalhes"),
        ("Details", "Detalhes"),
        ("notice", "aviso"),
        ("Notice", "Aviso"),
        ("warning", "aviso"),
        ("Warning", "Aviso"),
        ("report", "relatorio"),
        ("Report", "Relatorio"),
        ("safety", "seguranca"),
        ("cabinet", "armario"),
        ("Cabinet", "Armario"),
        ("storage", "armazem"),
        ("Storage", "Armazem"),
        ("bulletin board", "quadro de avisos"),
        ("Bulletin Board", "Quadro de Avisos"),
        ("bulletin", "quadro"),
        ("board", "quadro"),
        ("memo", "memorando"),
        ("Memo", "Memorando"),
        ("recently", "recentemente"),
        ("suspect", "suspeito"),
        ("criminal", "criminoso"),
        ("victim", "vitima"),
        ("mayor", "prefeito"),
        ("Mayor", "Prefeito"),
        ("beach", "praia"),
        ("Beach", "Praia"),
        ("delicious", "delicioso"),
        ("design", "design"),
        ("designs", "designs"),
        ("genius", "genio"),
        ("method", "metodo"),
        ("explore", "explorar"),
        ("invented", "inventei"),
        ("remodel", "remodelar"),
        ("coupon", "cupom"),
        ("Coupon", "Cupom"),
        ("fee", "taxa"),
        ("cost", "custo"),
        ("Cost", "Custo"),
        ("price", "preco"),
        ("Price", "Preco"),
        ("free", "gratis"),
        ("Free", "Gratis"),
        ("available", "disponivel"),
        ("possible", "possivel"),
        ("impossible", "impossivel"),
        ("necessary", "necessario"),
        ("qualified", "qualificado"),

        # Body parts / misc
        ("foot", "pe"),
        ("hand", "mao"),
        ("eye", "olho"),
        ("eyes", "olhos"),
        ("head", "cabeca"),
        ("heart", "coracao"),
        ("body", "corpo"),
        ("blood", "sangue"),
        ("soul", "alma"),
        ("spirit", "espirito"),
        ("mind", "mente"),
        ("memory", "memoria"),
        ("memories", "memorias"),

        # Emotions and states
        ("fear", "medo"),
        ("hope", "esperanca"),
        ("peace", "paz"),
        ("war", "guerra"),
        ("chaos", "caos"),
        ("pain", "dor"),
        ("joy", "alegria"),
        ("love", "amor"),
        ("hate", "odio"),
        ("anger", "raiva"),
        ("trust", "confianca"),
        ("dream", "sonho"),

        # Directions
        ("north", "norte"),
        ("North", "Norte"),
        ("south", "sul"),
        ("South", "Sul"),
        ("east", "leste"),
        ("East", "Leste"),
        ("west", "oeste"),
        ("West", "Oeste"),

        # Numbers/amounts in context
        ("once", "uma vez"),
        ("twice", "duas vezes"),

        # Common endings
        ("anymore", "mais"),
        ("indeed", "de fato"),
        ("however", "porem"),
        ("However", "Porem"),
        ("therefore", "portanto"),
        ("Therefore", "Portanto"),
        ("although", "embora"),
        ("Although", "Embora"),
        ("otherwise", "caso contrario"),
        ("Otherwise", "Caso contrario"),
        ("instead", "ao inves"),
        ("Instead", "Ao inves"),
        ("meanwhile", "enquanto isso"),
        ("Meanwhile", "Enquanto isso"),

        # Misc common words
        ("an ", "um "),
        ("An ", "Um "),
        ("a ", "um "),
        ("the ", "o "),
        ("The ", "O "),
        ("this ", "este "),
        ("This ", "Este "),
        ("that ", "esse "),
        ("That ", "Esse "),
        ("these ", "estes "),
        ("These ", "Estes "),
        ("those ", "esses "),
        ("Those ", "Esses "),
        ("my ", "meu "),
        ("My ", "Meu "),
        ("your ", "seu "),
        ("Your ", "Seu "),
        ("our ", "nosso "),
        ("Our ", "Nosso "),
        ("their ", "o "),
        ("his ", "o "),
        ("His ", "O "),
        ("her ", "a "),
        ("Her ", "A "),
        ("its ", "seu "),

        # Verbs continued
        ("has been", "tem sido"),
        ("have been", "tem sido"),
        ("will be", "sera"),
        ("would be", "seria"),
        ("could be", "poderia ser"),
        ("should be", "deveria ser"),
        ("must be", "deve ser"),
        ("might be", "pode ser"),
        ("may be", "pode ser"),
        ("going to", "vai"),
        ("able to", "capaz de"),
        ("want to", "quer"),
        ("need to", "precisa"),
        ("have to", "tem que"),
        ("had to", "teve que"),
        ("used to", "costumava"),
        ("trying to", "tentando"),
        ("looking for", "procurando"),
        ("waiting for", "esperando"),
        ("asking for", "pedindo"),
        ("getting", "ficando"),
        ("becoming", "se tornando"),
        ("doing", "fazendo"),
        ("going", "indo"),
        ("coming", "vindo"),
        ("making", "fazendo"),
        ("taking", "levando"),
        ("giving", "dando"),
        ("telling", "dizendo"),
        ("saying", "dizendo"),
        ("knowing", "sabendo"),
        ("thinking", "pensando"),
        ("living", "vivendo"),
        ("dying", "morrendo"),
        ("fighting", "lutando"),
        ("running", "correndo"),
        ("walking", "andando"),
        ("standing", "de pe"),
        ("sitting", "sentado"),
        ("sleeping", "dormindo"),
        ("eating", "comendo"),
        ("drinking", "bebendo"),
        ("playing", "jogando"),
        ("learning", "aprendendo"),
        ("teaching", "ensinando"),
        ("helping", "ajudando"),
        ("working", "trabalhando"),
        ("moving", "movendo"),
        ("changing", "mudando"),
        ("growing", "crescendo"),
        ("falling", "caindo"),
        ("rising", "subindo"),
        ("turning", "virando"),
        ("opening", "abrindo"),
        ("closing", "fechando"),
        ("building", "construindo"),
        ("breaking", "quebrando"),
        ("losing", "perdendo"),
        ("winning", "vencendo"),
        ("holding", "segurando"),
        ("keeping", "mantendo"),
        ("letting", "deixando"),
        ("passing", "passando"),
        ("paying", "pagando"),
        ("selling", "vendendo"),
        ("buying", "comprando"),
        ("wearing", "vestindo"),
        ("reading", "lendo"),
        ("writing", "escrevendo"),
        ("sending", "enviando"),
        ("receiving", "recebendo"),
        ("calling", "chamando"),
        ("meeting", "encontrando"),
        ("showing", "mostrando"),
        ("hearing", "ouvindo"),
        ("feeling", "sentindo"),
        ("seeing", "vendo"),
        ("believing", "acreditando"),
        ("reaching", "alcancando"),
        ("increasing", "aumentando"),
    ]

    # Apply word-boundary-aware replacements
    for eng, ptbr in replacements:
        # Use word boundary for standalone words, but simple replacement for phrases with spaces
        if ' ' in eng or eng.endswith("'s") or eng.endswith("'t") or eng.endswith("'m") or eng.endswith("'re") or eng.endswith("'ve") or eng.endswith("'ll") or eng.endswith("'d"):
            t = t.replace(eng, ptbr)
        else:
            # Word boundary replacement to avoid partial matches
            pattern = r'\b' + re.escape(eng) + r'\b'
            t = re.sub(pattern, ptbr, t)

    return t


def translate_select_content(content):
    """Translate the content inside select() calls."""
    # Handle select("opt1:opt2:opt3") format
    # and select("opt1", "opt2", "opt3") format
    options = content.split(':')
    translated = []
    for opt in options:
        translated.append(translate_text(opt))
    return ':'.join(translated)


def process_file(filepath):
    """Process a single NPC script file."""
    with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
        lines = f.readlines()

    modified = False
    new_lines = []

    for line in lines:
        original_line = line

        # Skip comments
        stripped = line.lstrip()
        if stripped.startswith('//'):
            new_lines.append(line)
            continue

        # Process mes "..." lines
        # Match: mes "text"; or mes "text";  with optional whitespace
        mes_match = re.match(r'^(\s*mes\s+")(.*)(";?\s*)$', line)
        if mes_match:
            prefix = mes_match.group(1)
            text = mes_match.group(2)
            suffix = mes_match.group(3)

            # Don't translate NPC name lines like [Name]
            stripped_text = text.strip()

            # Translate the text
            translated = translate_text(text)

            if translated != text:
                line = prefix + translated + suffix
                modified = True
            new_lines.append(line)
            continue

        # Process select() calls - can span multiple patterns
        # Pattern 1: select("opt1:opt2:opt3")
        select_match = re.search(r'(select\()"([^"]*)"(\))', line)
        if select_match:
            before = line[:select_match.start()]
            prefix = select_match.group(1)
            content = select_match.group(2)
            suffix = select_match.group(3)
            after = line[select_match.end():]

            translated_content = translate_select_content(content)
            if translated_content != content:
                line = before + prefix + '"' + translated_content + '"' + suffix + after
                modified = True
            new_lines.append(line)
            continue

        # Pattern 2: select("opt1", "opt2", "opt3")
        select_match2 = re.search(r'select\(\s*"', line)
        if select_match2:
            # Find all quoted strings within this select call
            def translate_select_option(m):
                text = m.group(1)
                translated = translate_text(text)
                return '"' + translated + '"'

            # Find the select(...) portion
            sel_start = select_match2.start()
            # Find matching closing paren
            depth = 0
            sel_end = sel_start
            for i in range(sel_start, len(line)):
                if line[i] == '(':
                    depth += 1
                elif line[i] == ')':
                    depth -= 1
                    if depth == 0:
                        sel_end = i + 1
                        break

            select_portion = line[sel_start:sel_end]
            translated_select = re.sub(r'"([^"]*)"', translate_select_option, select_portion)

            if translated_select != select_portion:
                line = line[:sel_start] + translated_select + line[sel_end:]
                modified = True
            new_lines.append(line)
            continue

        # Also handle callsub lines that have quoted text (quest descriptions)
        callsub_match = re.search(r'(callsub\s+\w+,\d+,")(.*)(";?)', line)
        if callsub_match:
            prefix = line[:callsub_match.start(2)]
            text = callsub_match.group(2)
            suffix = line[callsub_match.end(2):]

            translated = translate_text(text)
            if translated != text:
                line = prefix + translated + suffix
                modified = True
            new_lines.append(line)
            continue

        new_lines.append(line)

    if modified:
        with open(filepath, 'w', encoding='utf-8', newline='\n') as f:
            f.writelines(new_lines)
        return True
    return False


def main():
    base_dir = r'N:/Users/tinch/Documents/Projetos/ragnarok/npc/re/quests/'

    # Find all .txt files
    files = []
    for root, dirs, filenames in os.walk(base_dir):
        for fn in filenames:
            if fn.endswith('.txt'):
                files.append(os.path.join(root, fn))

    files.sort()

    # Skip already translated files
    skip_files = []
    for fp in files:
        with open(fp, 'r', encoding='utf-8', errors='replace') as f:
            content = f.read()
        if 'Cancelar' in content or 'voce' in content:
            skip_files.append(fp)

    print(f"Found {len(files)} files total")
    print(f"Skipping {len(skip_files)} already translated files")

    translated_count = 0
    for fp in files:
        if fp in skip_files:
            print(f"  SKIP: {fp}")
            continue

        result = process_file(fp)
        if result:
            translated_count += 1
            print(f"  TRANSLATED: {fp}")
        else:
            print(f"  NO CHANGES: {fp}")

    print(f"\nDone! Translated {translated_count} files.")


if __name__ == '__main__':
    main()
