import os
import re

BASE = "N:/Users/tinch/Documents/Projetos/ragnarok"

TRANSLATIONS = {
    "Ah, ok I think you can help me out by hunting some Caramels.": "Ah, ok, acho que voce pode me ajudar cacando alguns Caramels.",
    "Ah, ok I think you can help me out by hunting some Cocos.": "Ah, ok, acho que voce pode me ajudar cacando alguns Cocos.",
    "Ah, ok I think you can help me out by hunting some Creamys.": "Ah, ok, acho que voce pode me ajudar cacando alguns Creamys.",
    "Ah, ok I think you can help me out by hunting some Demon Pungus.": "Ah, ok, acho que voce pode me ajudar cacando alguns Demon Pungus.",
    "Ah, ok I think you can help me out by hunting some Dokebis.": "Ah, ok, acho que voce pode me ajudar cacando alguns Dokebis.",
    "Ah, ok I think you can help me out by hunting some Dryads.": "Ah, ok, acho que voce pode me ajudar cacando alguns Dryads.",
    "Ah, ok I think you can help me out by hunting some Fabres.": "Ah, ok, acho que voce pode me ajudar cacando alguns Fabres.",
    "Ah, ok I think you can help me out by hunting some Frilldora.": "Ah, ok, acho que voce pode me ajudar cacando alguns Frilldora.",
    "Ah, ok I think you can help me out by hunting some Golems.": "Ah, ok, acho que voce pode me ajudar cacando alguns Golems.",
    "Ah, ok I think you can help me out by hunting some Hodes.": "Ah, ok, acho que voce pode me ajudar cacando alguns Hodes.",
    "Ah, ok I think you can help me out by hunting some Leaf Cats.": "Ah, ok, acho que voce pode me ajudar cacando alguns Leaf Cats.",
    "Ah, ok I think you can help me out by hunting some Peco Pecos.": "Ah, ok, acho que voce pode me ajudar cacando alguns Peco Pecos.",
    "Amazing you found so many that fast.": "Incrivel, voce encontrou tantos tao rapido.",
    "And lets be honest, you are not the prettiest looking face I've seen.": "E sejamos honestos, voce nao tem a cara mais bonita que eu ja vi.",
    "Are you trying to scam me?": "Voce esta tentando me enganar?",
    "Bill of Birds but lately they seem": "Bill of Birds mas ultimamente eles parecem",
    "But now it is of a different nature.": "Mas agora e de uma natureza diferente.",
    "Can you collect ^00CE0025 Chrysalis^000000 and return them to me, I promise to reward you well.": "Voce pode coletar ^00CE0025 Chrysalis^000000 e traze-los para mim? Prometo recompensa-lo bem.",
    "Can you do me a favor please?": "Voce pode me fazer um favor, por favor?",
    "Can you do what you can to help me?": "Voce pode fazer o que puder para me ajudar?",
    "Can you get a little taller then return?": "Voce pode crescer um pouco mais e voltar?",
    "Can you help by collecting ^FF0000Bacillus^000000?": "Voce pode ajudar coletando ^FF0000Bacillus^000000?",
    "Can you help me find ^00CE0025 Acorns^000000.": "Voce pode me ajudar a encontrar ^00CE0025 Acorns^000000.",
    "Can you help me out and bring me ^FF000025 Bill of Birds^000000?": "Voce pode me ajudar e trazer ^FF000025 Bill of Birds^000000?",
    "Can you help protect me by killing them?": "Voce pode me proteger matando eles?",
    "Come back when you are stronger and have earned much more wisdom.": "Volte quando for mais forte e tiver ganhado muito mais sabedoria.",
    "Come back when you are taller and stronger.": "Volte quando for mais alto e mais forte.",
    "Currently the Situation is stable and i'm not in need of your help anymore to kill them.": "Atualmente a situacao esta estavel e nao preciso mais da sua ajuda para mata-los.",
    "Do you have any?": "Voce tem algum?",
    "Do you mind helping me get rid of some Pupa to clear out this field?": "Voce se importa de me ajudar a se livrar de alguns Pupa para limpar esse campo?",
    "Do you think you can help me with something?": "Voce acha que pode me ajudar com algo?",
    "Do you think you can help me?": "Voce acha que pode me ajudar?",
    "Do you think you could help me?": "Voce acha que poderia me ajudar?",
    "Gimme Gimme!!!": "Me da, me da!!!",
    "Go kill more Porings!": "Va matar mais Porings!",
    "Good Morning!": "Bom dia!",
    "Great! I knew the moment i saw you that i can count on you!": "Otimo! Eu sabia no momento que te vi que podia contar com voce!",
    "Great, you have enough!": "Otimo, voce tem o suficiente!",
    "Greetings citizen!": "Saudacoes cidadao!",
    "Have you gotten rid of the Pupa?": "Voce se livrou dos Pupa?",
    "Hello": "Ola",
    "Hello, my name is Langry.": "Ola, meu nome e Langry.",
    "Hello, my name is Yullo.": "Ola, meu nome e Yullo.",
    "Hello. DO you think you could help me?": "Ola. Voce acha que poderia me ajudar?",
    "Here is that reward I promised you, I hope take this wisdom I have passed on to you and share it with others.": "Aqui esta a recompensa que prometi, espero que leve essa sabedoria que passei para voce e compartilhe com outros.",
    "Here is what I promised you.": "Aqui esta o que eu prometi.",
    "Here you go, as promised.": "Aqui esta, como prometido.",
    "Hey do you think you can help me?": "Ei, voce acha que pode me ajudar?",
    "Hey there cutie!": "Ei, fofinho!",
    "Hey there.": "Ei, ola.",
    "Hey, I'm not playing, you better not hold out on me.": "Ei, nao estou brincando, e melhor nao esconder nada de mim.",
    "Hey, it looks like that the weight on": "Ei, parece que o peso nas",
    "Hey, thank you again.": "Ei, obrigado novamente.",
    "Hey, thank you.": "Ei, obrigado.",
    "Hey, you there. Yeah you!": "Ei, voce ai. Sim, voce!",
    "Hey, your a sweet little thing.": "Ei, voce e uma coisinha doce.",
    "Hi there.": "Oi.",
    "Hmm, I don't think you've gotten rid of 100 Pupa ainda...": "Hmm, acho que voce ainda nao se livrou de 100 Pupa...",
    "Hmm, I don't think you've gotten rid of 150 Pupa ainda...": "Hmm, acho que voce ainda nao se livrou de 150 Pupa...",
    "Hmm, I don't think you've gotten rid of 50 Pupa ainda...": "Hmm, acho que voce ainda nao se livrou de 50 Pupa...",
    "Hmm, this maybe a little much of a request for you.": "Hmm, isso talvez seja um pedido um pouco demais para voce.",
    "Hmmm... you seem to be too strong to be fighting over here.": "Hmmm... voce parece ser forte demais para estar lutando por aqui.",
    "How many Goats would you like to hunt?": "Quantos Goats voce gostaria de cacar?",
    "How many would you like to get rid of?": "De quantos voce gostaria de se livrar?",
    "I am looking for lizard ^FF0000Frills^000000.": "Estou procurando ^FF0000Frills^000000 de lagarto.",
    "I am so afraid that these Peco Pecos will hurt me for my, uh, researching activities.": "Tenho tanto medo que esses Peco Pecos me machuquem por minhas, uh, atividades de pesquisa.",
    "I am still doing my, uh, research...": "Ainda estou fazendo minha, uh, pesquisa...",
    "I am truly grateful.": "Sou verdadeiramente grato.",
    "I am trying to collect ^00CE0025 Earthworm Peelings^000000.": "Estou tentando coletar ^00CE0025 Earthworm Peelings^000000.",
    "I am trying to make my way through but I can't seem to get past these Demon Pungus.": "Estou tentando passar por aqui mas nao consigo ultrapassar esses Demon Pungus.",
    "I can't believe I am stuck doing this.": "Nao acredito que estou preso fazendo isso.",
    "I can't, no more and I mean it.": "Nao aguento mais, e estou falando serio.",
    "I don't see any ^00CE00Earthworm Peerlings^000000.": "Nao vejo nenhum ^00CE00Earthworm Peerlings^000000.",
    "I had my doubts, but you have proven me wrong.": "Eu tinha minhas duvidas, mas voce me provou errado.",
    "I have to complete this community service, but I am just too lazy.": "Tenho que completar esse servico comunitario, mas sou preguicoso demais.",
    "I just wish I could get through this all.": "Eu so queria conseguir passar por tudo isso.",
    "I know that I could've probably done this myself but it's not easy to be standing here all of the time.": "Sei que provavelmente poderia ter feito isso sozinho, mas nao e facil ficar aqui o tempo todo.",
    "I need ^00CE0025 Acorns^000000.": "Eu preciso de ^00CE0025 Acorns^000000.",
    "I need ^00CE0025 Chrysalis^000000 and no less please.": "Eu preciso de ^00CE0025 Chrysalis^000000, nao menos, por favor.",
    "I need ^00CE0025 Chrysalis^000000.": "Eu preciso de ^00CE0025 Chrysalis^000000.",
    "I need ^00CE0025 Earthworm Peelings^000000.": "Eu preciso de ^00CE0025 Earthworm Peelings^000000.",
    "I need ^00CE0025 Fluff^000000.": "Eu preciso de ^00CE0025 Fluff^000000.",
    "I need ^00CE0025 Porcupine Quills^000000.": "Eu preciso de ^00CE0025 Porcupine Quills^000000.",
    "I need ^00CE0050 Huge Leafs^000000.": "Eu preciso de ^00CE0050 Huge Leafs^000000.",
    "I need ^00CE0050 Sharp Leafs^000000.": "Eu preciso de ^00CE0050 Sharp Leafs^000000.",
    "I need ^FF000025 Frills^000000 for the Assassin's Guild.": "Eu preciso de ^FF000025 Frills^000000 para a Guilda dos Assassinos.",
    "I need ^FF000050 Dokebi Horns^000000 for my fortune telling.": "Eu preciso de ^FF000050 Dokebi Horns^000000 para minha leitura da sorte.",
    "I need ^FF0000Antelope Horns^000000 to show for your hard work, and I will reward you.": "Eu preciso de ^FF0000Antelope Horns^000000 para mostrar seu trabalho duro, e vou te recompensar.",
    "I need some ^FF0000Bill of Birds^000000 for my, uh, research...": "Eu preciso de alguns ^FF0000Bill of Birds^000000 para minha, uh, pesquisa...",
    "I need to collect ^0000CE25 Fluff^000000 to": "Eu preciso coletar ^0000CE25 Fluff^000000 para",
    "I need to have a good supply of ^FF0000Powder of Butterfly^000000": "Eu preciso ter um bom estoque de ^FF0000Powder of Butterfly^000000",
    "I need to see that you have gathered ^FF000050 Antelope Horns^000000, and then I can reward you.": "Preciso ver que voce juntou ^FF000050 Antelope Horns^000000, e entao posso te recompensar.",
    "I need to see that you have gathered ^FF000050 Bacillus^000000, and then I can reward you.": "Preciso ver que voce juntou ^FF000050 Bacillus^000000, e entao posso te recompensar.",
    "I need you to reduce the Amount of Monsters which are currently rampaging on this Map!": "Preciso que voce reduza a quantidade de monstros que estao causando caos neste mapa!",
    "I read fortunes in Payon.": "Eu leio a sorte em Payon.",
    "I really need to gather ^00CE0050 Huge Leafs^000000 for my sanity.": "Eu realmente preciso juntar ^00CE0050 Huge Leafs^000000 pela minha sanidade.",
    "I really need to gather ^00CE0050 Sharp Leafs^000000 for my garden tea party.": "Eu realmente preciso juntar ^00CE0050 Sharp Leafs^000000 para minha festa do cha no jardim.",
    "I see no Fluff, wait yea I do it's the lies coming from your mouth.": "Nao vejo nenhum Fluff, espera, sim eu vejo, sao as mentiras saindo da sua boca.",
    "I think I'll feel safer...": "Acho que vou me sentir mais seguro...",
    "I think that I can rest easily now.": "Acho que posso descansar tranquilo agora.",
    "I will give you some medical supplies.": "Vou te dar alguns suprimentos medicos.",
    "I will reward you for helping clear this out for me.": "Vou te recompensar por me ajudar a limpar isso.",
    "I will reward you if you help.": "Vou te recompensar se ajudar.",
    "I will reward you with much if you can.": "Vou te recompensar bastante se conseguir.",
    "I work for an apothecary in Prontera": "Eu trabalho para um boticario em Prontera",
    "I work for an apothecary in Prontera.": "Eu trabalho para um boticario em Prontera.",
    "I..I just can't seem to find any.": "Eu... simplesmente nao consigo encontrar nenhum.",
    "I come here to collect materials for medicine.": "Venho aqui coletar materiais para remedios.",
    "If not, i don't know what to do with the Monsters in this Place!": "Se nao, nao sei o que fazer com os monstros neste lugar!",
    "If not, then I am in a world of hurt.": "Se nao, estou em serios problemas.",
    "If you bring me": "Se voce me trouxer",
    "If you bring me ^FF000025 Powder of Butterfly^000000,": "Se voce me trouxer ^FF000025 Powder of Butterfly^000000,",
    "If you can get rid of 100 of those Pupa from the field I will be grateful.": "Se voce puder se livrar de 100 desses Pupa do campo, ficarei grato.",
    "If you can get rid of 150 of those Pupa from the field I will be grateful.": "Se voce puder se livrar de 150 desses Pupa do campo, ficarei grato.",
    "If you can get rid of 50 of those Pupa from the field I will be grateful.": "Se voce puder se livrar de 50 desses Pupa do campo, ficarei grato.",
    "It doesn't look like you have enough.": "Parece que voce nao tem o suficiente.",
    "It is dangerous here citizen.": "E perigoso aqui, cidadao.",
    "Its amazing, truly it is.": "E incrivel, realmente e.",
    "Just like I promised a little reward.": "Como prometi, uma pequena recompensa.",
    "Kill 100 of those Goats and let me know when you're done. I will reward you for your efforts.": "Mate 100 desses Goats e me avise quando terminar. Vou te recompensar pelos seus esforcos.",
    "Kill 150 of those Goats and let me know when you're done. I will reward you for your efforts.": "Mate 150 desses Goats e me avise quando terminar. Vou te recompensar pelos seus esforcos.",
    "Kill 50 of those Disguise and let me know when you're done. I will reward you for your efforts.": "Mate 50 desses Disguise e me avise quando terminar. Vou te recompensar pelos seus esforcos.",
    "Kill 50 of those Goats and let me know when you're done. I will reward you for your efforts.": "Mate 50 desses Goats e me avise quando terminar. Vou te recompensar pelos seus esforcos.",
    "Kill 50 of those Loli Ruri and let me know when you're done. I will reward you for your efforts.": "Mate 50 desses Loli Ruri e me avise quando terminar. Vou te recompensar pelos seus esforcos.",
    "Kill 50 of those Mantis and let me know when you're done. I will reward you for your efforts.": "Mate 50 desses Mantis e me avise quando terminar. Vou te recompensar pelos seus esforcos.",
    "Kill 50 of those Zhu Po Long and let me know when you're done. I will reward you for your efforts.": "Mate 50 desses Zhu Po Long e me avise quando terminar. Vou te recompensar pelos seus esforcos.",
    "Like I promised, give me the Chrysalis and I will reward you with my wisdom.": "Como prometi, me de os Chrysalis e vou te recompensar com minha sabedoria.",
    "Look at me I am serious I can't kill any more of these things.": "Olhe pra mim, estou falando serio, nao consigo matar mais nenhum desses bichos.",
    "Meow meow meow meow meow...": "Miau miau miau miau miau...",
    "My fortune teller business needs a good supply of ^FF0000Dokebi Horns^000000 to give my customers good luck.": "Meu negocio de adivinhacao precisa de um bom estoque de ^FF0000Dokebi Horns^000000 para dar sorte aos meus clientes.",
    "My vegetables, where did they all go?": "Meus vegetais, para onde foram todos?",
    "NOOOOOOOOOOOO.": "NAAAAAAOOOOO.",
    "New here are you?": "Novo por aqui?",
    "None-the-less my daughter thought it would be fun to gather pupa around this field and it's becoming unsightly.": "De qualquer forma, minha filha achou que seria divertido juntar pupas neste campo e esta ficando feio.",
    "Not sure why you are here, but I can't offer you a bounty as there would be no effort in it for you!": "Nao sei porque voce esta aqui, mas nao posso te oferecer recompensa pois nao seria nenhum esforco para voce!",
    "Now wait a minute, are you not a little too high of level for this?": "Espere um minuto, voce nao e de nivel alto demais para isso?",
    "Oh and here you go, this should help you get stronger, faster!": "Oh, e aqui esta, isso deve te ajudar a ficar mais forte, mais rapido!",
    "Oh boy, Oh boy!": "Que bom, que bom!",
    "Oh great you found out where they were hiding them.": "Otimo, voce descobriu onde eles estavam escondendo.",
    "Oh great!": "Que otimo!",
    "Oh thank you so much!": "Oh, muito obrigado!",
    "Oh thank you so much.": "Oh, muito obrigado.",
    "Oh that's right, sorry I just love roasting Acorns. Mmm.": "Ah, e verdade, desculpe, eu adoro assar bolotas. Mmm.",
    "Oh well, I haven't yet mastered my skills.": "Ah, bom, ainda nao dominei minhas habilidades.",
    "Oh, I almost forgot. I have something for you ^_^": "Oh, quase esqueci. Tenho algo para voce ^_^",
    "Oh, great!": "Oh, otimo!",
    "Oh, no..no!!!": "Oh, nao..nao!!!",
    "Oh, that's great! I knew I could count on you, just from looking at you!": "Oh, que otimo! Eu sabia que podia contar com voce, so de olhar para voce!",
    "Ok, so I need 25 Porcupine": "Ok, entao eu preciso de 25 Porcupine",
    "Peco Pecos are fascinating.": "Peco Pecos sao fascinantes.",
    "Peelings!": "Peelings!",
    "Perhaps you could help me?": "Talvez voce pudesse me ajudar?",
    "Pesky Coco's have hidden all the Acorns.": "Os Cocos chatos esconderam todas as bolotas.",
    "Please do not interrupt my mission for the Morocc Guard.": "Por favor, nao interrompa minha missao para a Guarda de Morocc.",
    "Please hurry and kill 100 of those tasty err pesky Peco Pecos.": "Por favor, se apresse e mate 100 daqueles saborosos, digo, chatos Peco Pecos.",
    "Please hurry and kill 150 of those tasty err pesky Peco Pecos.": "Por favor, se apresse e mate 150 daqueles saborosos, digo, chatos Peco Pecos.",
    "Please hurry and kill 50 of those tasty err pesky Peco Pecos.": "Por favor, se apresse e mate 50 daqueles saborosos, digo, chatos Peco Pecos.",
    "Please return to me when you are a little stronger.": "Por favor, volte quando estiver um pouco mais forte.",
    "Please tell me you have some or can": "Por favor, me diga que voce tem alguns ou pode",
    "Please, don't waste my time.": "Por favor, nao desperdice meu tempo.",
    "Please...": "Por favor...",
    "Please?": "Por favor?",
    "Quickly escape before they get their claws into your sanity!": "Fuja rapido antes que eles cravam as garras na sua sanidade!",
    "Quill's.": "Quill's.",
    "Really? What would you like to do to help?": "Serio? O que voce gostaria de fazer para ajudar?",
    "Really?!": "Serio?!",
    "Remember, get rid of 100 of those Pupa from the field.": "Lembre-se, livre-se de 100 desses Pupa do campo.",
    "Remember, get rid of 150 of those Pupa from the field.": "Lembre-se, livre-se de 150 desses Pupa do campo.",
    "Remember, get rid of 50 of those Pupa from the field.": "Lembre-se, livre-se de 50 desses Pupa do campo.",
    "Say, how would you like to help me?": "Diga, voce gostaria de me ajudar?",
    "Sigh,": "Suspiro,",
    "So, which of those Monsters would you like to hunt for me?": "Entao, qual desses monstros voce gostaria de cacar para mim?",
    "So, would you still like to help me?": "Entao, voce ainda gostaria de me ajudar?",
    "Sorry I can't talk right now I am in a world of hurt here, these darn Goats are going to kill me.": "Desculpe, nao posso falar agora, estou sofrendo muito, esses malditos Goats vao me matar.",
    "Sorry I can't talk right now I am in a world of pain here, these darn Disguise and Loli Ruri are going to kill me.": "Desculpe, nao posso falar agora, estou sofrendo muito, esses malditos Disguise e Loli Ruri vao me matar.",
    "Sorry I can't talk right now I am in a world of pain here, these darn Mantis are going to kill me.": "Desculpe, nao posso falar agora, estou sofrendo muito, esses malditos Mantis vao me matar.",
    "Sorry I can't talk right now I am in a world of pain here, these darn Zhu Po Long are going to kill me.": "Desculpe, nao posso falar agora, estou sofrendo muito, esses malditos Zhu Po Long vao me matar.",
    "Sorry but you are a little too old and scary to talk to!": "Desculpe, mas voce e um pouco velho e assustador demais para conversar!",
    "Thank you for the 25 Earthworm": "Obrigado pelas 25 Earthworm",
    "Thank you for the Fluff. This helps me out greatly.": "Obrigado pelo Fluff. Isso me ajuda muito.",
    "Thank you for the horns.": "Obrigado pelos chifres.",
    "Thank you for your great help with the Disguise!": "Obrigado pela sua grande ajuda com os Disguise!",
    "Thank you for your great help with the Loli Ruri!": "Obrigado pela sua grande ajuda com os Loli Ruri!",
    "Thank you for your great help with the Mantis!": "Obrigado pela sua grande ajuda com os Mantis!",
    "Thank you for your great help with the Zhu Po Long!": "Obrigado pela sua grande ajuda com os Zhu Po Long!",
    "Thank you for your offer though.": "Obrigado pela oferta mesmo assim.",
    "Thank you so much again for your help.": "Muito obrigado novamente pela sua ajuda.",
    "Thank you so much!": "Muito obrigado!",
    "Thank you so much.": "Muito obrigado.",
    "Thank you.": "Obrigado.",
    "Thanks a lot, pal!": "Muito obrigado, amigo!",
    "Thanks so much for helping me!": "Muito obrigado por me ajudar!",
    "Thanks! I really appreciate it.": "Obrigado! Eu realmente agradeco.",
    "Thanks! You're a life saver!": "Obrigado! Voce e um salva-vidas!",
    "That's great!": "Que otimo!",
    "The Morocc Guard needs ^FF000025 Stone Hearts^000000, for our training regimen.": "A Guarda de Morocc precisa de ^FF000025 Stone Hearts^000000, para nosso treinamento.",
    "The Morocc Guard needs ^FF0000Stone Hearts^000000 for our training regimen.": "A Guarda de Morocc precisa de ^FF0000Stone Hearts^000000 para nosso treinamento.",
    "The Morocc Guard thanks you, citizen.": "A Guarda de Morocc agradece, cidadao.",
    "The desert will kill you here!": "O deserto vai te matar aqui!",
    "The lizards around here have a natural stealth, a property that the Assassin's Guild wants to study.": "Os lagartos por aqui tem uma camuflagem natural, uma propriedade que a Guilda dos Assassinos quer estudar.",
    "The more leafs I collect the quieter it seems around here.": "Quanto mais folhas eu coleto, mais calmo parece ficar por aqui.",
    "There are so many Dokebis here...I just don't feel safe.": "Ha tantos Dokebis aqui... simplesmente nao me sinto seguro.",
    "There are to many Disguise and Loli Ruri around, which makes it impossible for the lower level players to gain good experience here.": "Ha muitos Disguise e Loli Ruri por aqui, o que torna impossivel para jogadores de nivel mais baixo ganhar boa experiencia aqui.",
    "There are to many Mantis around, which makes it impossible for the lower level players to gain good experience here.": "Ha muitos Mantis por aqui, o que torna impossivel para jogadores de nivel mais baixo ganhar boa experiencia aqui.",
    "There are to many Zhu Po Long around, which makes it impossible for the lower level players to gain good experience here.": "Ha muitos Zhu Po Long por aqui, o que torna impossivel para jogadores de nivel mais baixo ganhar boa experiencia aqui.",
    "These Goats keep eating my vegetables.": "Esses Goats continuam comendo meus vegetais.",
    "These are pretty icky though.": "Esses sao bem nojentos, porem.",
    "These lizards are gross.": "Esses lagartos sao nojentos.",
    "Think you could take some time to give me a hand?": "Acha que poderia tirar um tempo para me dar uma mao?",
    "This is gonna be delicious!": "Isso vai ser delicioso!",
    "This place is dangerous!": "Este lugar e perigoso!",
    "Those picky's over there seem to be about your speed.": "Aqueles Pickys ali parecem ser do seu nivel.",
    "Um, um. I don't think..": "Hm, hm. Eu nao acho que..",
    "Wait! You can see me?": "Espere! Voce pode me ver?",
    "Well look, I like helping new faces around here.": "Olha, eu gosto de ajudar rostos novos por aqui.",
    "What are you doing here?": "O que voce esta fazendo aqui?",
    "Where are my ^00CE00Acorns^000000?": "Onde estao minhas ^00CE00Acorns^000000?",
    "Where are the Porcupine Quills?": "Onde estao as Porcupine Quills?",
    "Why hello!": "Ora, ola!",
    "Why, I may look cute and silly but please don't play games with me.": "Olha, eu posso parecer fofo e bobo, mas por favor nao brinque comigo.",
    "Wonderful I can tell it is just a little bit quieter around here!": "Maravilhoso, da pra perceber que esta um pouco mais quieto por aqui!",
    "Yeah, sorry I can't talk right now.": "Sim, desculpe, nao posso falar agora.",
    "You are here to help me right?": "Voce esta aqui para me ajudar, certo?",
    "You are just too small to fight these things for me.": "Voce e muito pequeno para lutar contra essas coisas por mim.",
    "You are much to strong to be fighting these things!": "Voce e forte demais para lutar contra essas coisas!",
    "You are much too strong to be fighting these things!": "Voce e forte demais para lutar contra essas coisas!",
    "You are way too tiny to be helping me.": "Voce e muito pequeno para me ajudar.",
    "You can gather them and I can give you a reward for your efforts!": "Voce pode junta-los e eu posso te dar uma recompensa pelos seus esforcos!",
    "You could probably easily help me out, but I want to give charity to those who are not as strong as you.": "Voce provavelmente poderia me ajudar facilmente, mas quero dar oportunidade a quem nao e tao forte quanto voce.",
    "You know what, here is an idea.": "Sabe de uma coisa, tenho uma ideia.",
    "You know what? I can even reward you a little for helping me.": "Sabe de uma coisa? Posso ate te recompensar um pouco por me ajudar.",
    "You look like someone who is willing to help a lil thing like myself out.": "Voce parece alguem disposto a ajudar uma coisinha como eu.",
    "You look like someone who is willing to help someone who is slowly going mad.": "Voce parece alguem disposto a ajudar alguem que esta ficando louco aos poucos.",
    "You may just be the most unlikely person ever, recycle a few Fabres and come back.": "Voce pode ser a pessoa mais improvavel de todas, recicle alguns Fabres e volte.",
    "You need some help, but I can't provide that for you.": "Voce precisa de ajuda, mas nao posso te fornecer isso.",
    "You see I've been uh, ''researching''": "Sabe, eu tenho, uh, ''pesquisado''",
    "You should leave quickly!": "Voce deveria sair rapidamente!",
    "You think I wouldn't notice?": "Voce acha que eu nao ia perceber?",
    "Your level is too low!": "Seu nivel e muito baixo!",
    "^FF000050 Dokebi Horns^000000, I can give you some good luck.": "^FF000050 Dokebi Horns^000000, posso te dar um pouco de sorte.",
    "after you have lost some weight.": "depois de perder um pouco de peso.",
    "complete this community service project.": "completar este projeto de servico comunitario.",
    "help me": "me ajude",
    "these animals by collecting their": "esses animais coletando seus",
    "to have become hostile towards me.": "terem se tornado hostis comigo.",
    "your back will crush you. Come back": "suas costas vai te esmagar. Volte",
}

SELECT_TRANSLATIONS = {
    "What things?:Ignore.": "Que coisas?:Ignorar.",
    "I have Porcupine Quills:Well I don't think I can help.": "Eu tenho Porcupine Quills:Bom, acho que nao posso ajudar.",
    "I have 25 Acorns:Please come again?": "Eu tenho 25 Acorns:Como disse?",
    "I have Powder of Butterfly:What did you need?": "Eu tenho Powder of Butterfly:O que voce precisava?",
    "I have 25 Chrysalis:I don't have any.": "Eu tenho 25 Chrysalis:Nao tenho nenhum.",
    "I have the 25 Earthworm Peelings:No, I don't": "Eu tenho as 25 Earthworm Peelings:Nao, nao tenho",
    "I have 25 Fluff:I don't have Fluff.": "Eu tenho 25 Fluff:Nao tenho Fluff.",
    "I have the Frills:Lizards, gross!": "Eu tenho os Frills:Lagartos, nojento!",
    "I have 50 Dokebi Horns:I need to go now...": "Eu tenho 50 Dokebi Horns:Preciso ir agora...",
    "I have the Bill of Birds:Please, stop staring at me!": "Eu tenho os Bill of Birds:Por favor, pare de me encarar!",
    "I have the Bacillus:I don't have any": "Eu tenho os Bacillus:Nao tenho nenhum",
    "I have the Antelope Horns:Why are you out here?": "Eu tenho os Antelope Horns:Por que voce esta aqui?",
    "I have 50 Huge Leafs:I don't have enough.": "Eu tenho 50 Huge Leafs:Nao tenho o suficiente.",
    "I have 50 Sharp Leafs:I don't have enough.": "Eu tenho 50 Sharp Leafs:Nao tenho o suficiente.",
    "I have the Stone Hearts:I don't have Stone Hearts.": "Eu tenho os Stone Hearts:Nao tenho Stone Hearts.",
    "Sure:No Thanks.": "Claro:Nao, obrigado.",
    "Sure!:I don't think so.": "Claro!:Acho que nao.",
    "Sure!:No way!": "Claro!:De jeito nenhum!",
    "Sure, I'd love to help!:No, leave me alone.": "Claro, adoraria ajudar!:Nao, me deixe em paz.",
    "Hunt:Collect Items": "Cacar:Coletar Itens",
    "Gather Items:Hunt Pupa:Cancel": "Coletar Itens:Cacar Pupa:Cancelar",
    "Hunt Monsters:Collect Items:Cancel": "Cacar Monstros:Coletar Itens:Cancelar",
}

def process_file(filepath):
    with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
        content = f.read()

    original = content

    # Replace mes dialogue
    for eng, pt in TRANSLATIONS.items():
        old = 'mes "' + eng + '";'
        new = 'mes "' + pt + '";'
        content = content.replace(old, new)

    # Replace select options
    for eng, pt in SELECT_TRANSLATIONS.items():
        old = 'select("' + eng + '")'
        new = 'select("' + pt + '")'
        content = content.replace(old, new)

    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    return False

# Process collection quest files
collection_dir = os.path.join(BASE, "npc", "pre-re", "quests", "collection")
count = 0
for fn in sorted(os.listdir(collection_dir)):
    if fn.endswith('.txt'):
        fp = os.path.join(collection_dir, fn)
        if process_file(fp):
            count += 1
            print(f"Updated: {fn}")
        else:
            print(f"No changes: {fn}")

print(f"\nTotal collection files updated: {count}")
